### ISSUE TITLE
what chain file should be used?

### ISSUE THREAD

**Issue by lizihe21** [hillerlab/TOGA#1]
Hi!
Glad to see your new pipeline released.I am testing the pipeline and I notice that the pipeline use chain rather than maf as the input.I wonder whether original chain file or the filtered pre-net chain file should be used as the input .

**Comment by kirilenkobm** [comment]
Hi!
Thank you.

I would recommend to use the original chain file.

**Comment by lizihe21** [comment]
ok.
Thanks a lot

**Comment by saxovocal** [comment]
Hi I have a question about chain files as well. Suppose I need to generate a completely new chain file between two species; should I use the ucsc kent DoBlastzChainNet.pl, or would the pipeline from your lab GenomeAlignmentTools also work?

**Comment by kirilenkobm** [comment]
I would recommend to use one from GenomeAlignmentTools but kent DoBlastzChainNet.pl also fits.
