### ISSUE TITLE
visualization of inactivation mutations

### ISSUE THREAD

**Issue by yuzhenpeng** [hillerlab/TOGA#10]
Hellom, @MichaelHiller 

I met some questions on visualization of inactivation mutations. 
I just follow your instructions. 

First, the inactivation mutations of all genes in the 'inact_mut_data.txt'. I want to see one gene as followd command:
`python ~/opt/softwares/TOGA/supply/plot_mutations.py ~/mammals_genome_alignment/marine_mammals_lastz/hema/hg38.wgEncodeGencodeCompV34.bed ./inact_mut_data.hdf5 ENSG00000126351 ENST00000450525.svg -i ~/opt/softwares/TOGA/supply/hg38.wgEncodeGencodeCompV34.isoforms.txt`

But the out Figure only have transcripts, didn't have any mutations.
![image](https://user-images.githubusercontent.com/31943277/106109137-20df1400-6184-11eb-935a-a331d009d7d2.png)

Could you help me
Thank you.

**Comment by kirilenkobm** [comment]
The vis script was already modified many times, pls reopen if the issue is still relevant.
