### ISSUE TITLE
Using multiple query genomes?

### ISSUE THREAD

**Issue by sqwwww** [hillerlab/TOGA#107]
hello,

If I understand right, TOGA can only find orthologous relationship between two species(the reference species and the query species).
Is there a way to get  orthologous relationship between one reference species and multiple query species in one run?
or I should run many time, "ref sp vs query sp1","ref sp vs query sp2", ..., and then intersect these result to get a combined result.

**Comment by MichaelHiller** [comment]
"orthologous relationship between one reference species and multiple query species in one run" does not work as each TOGA run is independent.
But the latter ""ref sp vs query sp1","ref sp vs query sp2", ..., and then intersect these results:" would work.

**Comment by kirilenkobm** [comment]
To be explained here: https://github.com/hillerlab/TOGA/wiki/Usage-and-best-practices
