### ISSUE TITLE
TOGA data repo is forbidden

### ISSUE THREAD

**Issue by mchaney1** [hillerlab/TOGA#108]
Hello, I have run into an issue accessing your lab's data from the recent TOGA paper at this URL: https://genome.senckenberg.de/download/TOGA/. I am suddenly getting a 403-Forbidden error, but I had no issue accessing this repository at an earlier date. I would be grateful for any clarification on why this is happening.

Thanks for your time, and I look forward to hearing from you.

**Comment by MichaelHiller** [comment]
Thanks for reporting this. 
Looks like we have a hardware issue on this machine, likely related to a small power outage yesterday. 
We will try to fix it asap, but depending on what is broken, it may take a few days. 

I'll send a ping when it works again.

**Comment by MichaelHiller** [comment]
Hi Morgan, 
the issue is fixed and the download site + genome browsers work again.

**Comment by mchaney1** [comment]
Vielen Dank für Ihre Hilfe, Michael -- besonders dass Sie mir so schnell geantwortet haben! Ich habe es gerade gecheckt, und alles scheint in Ordnung zu sein 😁
