### ISSUE TITLE
Restarting without rerunning all jobs

### ISSUE THREAD

**Issue by mchaisso** [hillerlab/TOGA#11]
I'm running toga.py in the following manner:

../../TOGA/toga.py  /panfs/qcb-panasas/mchaisso/VGP/MuridaeComparativeAnalysis/PairwiseLastz/mm10_mArvNil.ucsc_params/align.axt.chain   /panfs/qcb-panasas/mchaisso/VGP/mm10/mm10.ncbiRefSeq.gtf.genePred.bed12  ../../PairwiseLastz/mm10.fa.2bit ../../PairwiseLastz/GCF_011762505.1_mArvNil1.pat.X_genomic.fna.2bit  --nextflow_config_dir /panfs/qcb-panasas/mchaisso/VGP/MuridaeComparativeAnalysis/TogaRuns/mm10_mArvNil/nextflow --do_not_del_nf_logs --nextflow_dir /panfs/qcb-panasas/mchaisso/VGP/MuridaeComparativeAnalysis/TogaRuns/mm10_mArvNil/nf --project_name toga-nileRat

It restarts the job from scratch each time it runs.  It has an error at the CESAR_wrapper.py step, which I can create a different issue for. Here I'm wondering if there are checkpoints or options to enable toga.py to restart where a previous command failed?

**Comment by kirilenkobm** [comment]
Currently, there are no traditional "checkpoints" implemented in the TOGA pipeline. Over 95% of the runtime is occupied by CESAR jobs, making the runtime of steps before and after CESAR negligible. As such, there hasn't been a strong need for checkpoints. However, I had a script available to execute everything "after the CESAR step," which could be useful in certain scenarios, such as development.

Your suggestion to better manage CESAR jobs, such as executing only the failed ones, is a reasonable and valuable improvement. We will consider implementing this feature in the future.
