### ISSUE TITLE
Genes annotated in GTF file but can not find from the TOGA generated bed file

### ISSUE THREAD

**Issue by liuxiaojieyx** [hillerlab/TOGA#114]
Dear,
I use Zebrafish as reference genome  to identify the gene ortholog in different fish genomes. However, I find many genes are not annotated in the bed file generated by TOGA when we compared the output .bed file with the original genome annotate GTF file. The chain file was generated by default parameters. And I attached the TOGA script I used in the analysis.  I had thought its because the huge divergent between the fish genome and chain file is not good at that region. However, I manually checked the chain file, the targeted region mapped quite well. The following pictures is the file visualised in IGV. The query_annotateion.bed is the file generated by TOGA and the Esoxxx.gtf is the genome annotation file. We expect this region is quite conserved (one chain , however, the gene ENSELUT00000000878 which we want to analyze further is missed in the bed file. Actually, Zebrafish has 2 copies of this gene at the region in the red-box marked region. The two copies are short (~3kb) with quite short introns. And the Esox_lucius has one ortholog copy which has large introns as indicated in the picture. Do you know the reason for this? And how could I modify the parameters to make the gene annotated? 

![image](https://github.com/hillerlab/TOGA/assets/148746834/9f8af498-a8dc-4e7a-b1c1-18e01f108d1d)
./toga.py ../Make_lastz_chains/make_lastz_chains-main//dare_dapemasked/dare.eslu.allfilled.chain  ../genomes/dare/danRer11_Ensembl.Dec_14_2021.bed ../genomes/dare/danRer11.fa.2bit ../genomes/eslu/eslu.fasta.editheader.masked.2bit --kt --pn dare_eslu_masked --cb 8,16,32,64 --ms --cjn 32 --do_not_del_nf_logs --ces

**Comment by MichaelHiller** [comment]
Hi, 

I would like to note that the difference between zebrafish and esox is likely similar to human-chicken (~1 subs per neutral site (https://pubmed.ncbi.nlm.nih.gov/23814184/).  TOGA may not be optimal for such distances, as introns are likely very diverged and only gene synteny is what TOGA seems to use to infer orthologs. 

Anyway, to better understand this case, can you pls send a screenshot showing this locus in zebrafish and the alignment chains? Then we see what actually aligns. 

Also, pls have a look at the loss_summ_data.tsv and orthology_classification.tsv. 
If you have the chain ID, the temp/chain_results_df.tsv tells you the orthology probability. 

Thx

**Comment by liuxiaojieyx** [comment]
[TOGA issue.pptx](https://github.com/hillerlab/TOGA/files/13275097/TOGA.issue.pptx)
Dear, 
Thanks for your quick answer. I made a brief slide to elucidate the issue I met in the analysis. Hope it is clear.

**Comment by MichaelHiller** [comment]
Thanks for sending this. Based on the loss file, both of your focal genes are classified as lost.
Can you pls grep these genes from inact_mut_data.txt ? Then we understand whether TOGA identifies an aligning locus and finds inactivating mutations or whether both genes are entirely deleted (then it could be a problem with the chains).

Do you have a way of visualizing the chains? That would help a lot. 
What is your reference zfish assembly?

**Comment by liuxiaojieyx** [comment]
Hi, thanks for the answer. This is how it looks like in the inact_mut_data.txt. Currently, I have no idea to visualize the genome chain file. Maybe only choromosome16 of zfish to choromosome 20 of esox? The zfish is the newest one, V11. 
![image](https://github.com/hillerlab/TOGA/assets/148746834/8cf53a24-a286-420f-a1ce-30a62fd3dc35)

**Comment by MichaelHiller** [comment]
OK, this shows what I was suspecting, meaning both genes are classified as deleted. The chains then likely don't show any alignments. 

If your zfish reference is danRer11 (https://genome.ucsc.edu/cgi-bin/hgTracks?db=danRer11), then pls send me the chain.gz file. I'll try to visualize that in the browser. 

I'll see if I can re-run the chains, maybe for this locus. 
Is your esox assembly available on NCBI?

**Comment by liuxiaojieyx** [comment]
Hi, 
Its true that I am using danRer11 version. Here is the link of the chain file I created for Zfish and Esox: https://we.tl/t-fmEdNP54TC. And the genome fasta file I downloaded from here https://ftp.ensembl.org/pub/release-110/fasta/esox_lucius/dna/Esox_lucius.Eluc_v4.dna_sm.toplevel.fa.gz, The corresponding GTF file I downloaded here. https://ftp.ensembl.org/pub/release-110/gtf/esox_lucius/Esox_lucius.Eluc_v4.110.chr.gtf.gz

**Comment by MichaelHiller** [comment]
I loaded the chains. This is how ENSDART00000179865 looks like in danRer11
![image](https://github.com/hillerlab/TOGA/assets/8644098/c1067f7a-7c16-4594-94e7-c80e6d3c9e14)

The top chain (ID 183) shows that barely any intronic or intergenic region aligns, indicating that zebrafish and esox are likely rather distant. TOGA is powerful for closer species comparisons where some neutrally evolving introns/intergenic regions still align. 

Nevertheless, there is conserved synteny across the neighboring genes and for the focal ENSDART00000179865 gene, the coding exons align. 
Therefore, I don't understand right now, why TOGA detects a deletion for this gene. 

Did you generate the chains with https://github.com/hillerlab/make_lastz_chains and sensitive parameters?

**Comment by liuxiaojieyx** [comment]
Hi,
Indeed, I generate the chain file with make_lastz_chains with default parameters. Should I add some extra parameters to make it more sensitive?
Here is the code I am using: make_chains.py danRer11 esox danRer11.2bit esox.2bit --project_dir test

**Comment by MichaelHiller** [comment]
OK, I'll try to run chains myself. 
Quickly: Is the esox assembly this? GCF_004634155.1 
(if so, VGP has a better assembly GCF_011004845)

**Comment by liuxiaojieyx** [comment]
The Esox genome fasta file I downloaded from here https://ftp.ensembl.org/pub/release-110/fasta/esox_lucius/dna/Esox_lucius.Eluc_v4.dna_sm.toplevel.fa.gz, The corresponding GTF file I downloaded here. https://ftp.ensembl.org/pub/release-110/gtf/esox_lucius/Esox_lucius.Eluc_v4.110.chr.gtf.gz.

**Comment by MichaelHiller** [comment]
Right, but is this the assembly that NCBI lists under GCF_004634155.1? 
Would be easier for me to get it from NCBI

**Comment by liuxiaojieyx** [comment]
Indeed, just checked, the version I used in NCBI is GCF_004634155.1. Thanks a lot.

**Comment by MichaelHiller** [comment]
I started masking and alignment. 
Can you pls send me the annotation you used for danRer11? (bed and isoform file)
Thx

**Comment by liuxiaojieyx** [comment]
Here is the bed file I used for Zfish_v11. https://we.tl/t-kvOIHOPSFP. I did not utilize the isoform file during the analysis.

**Comment by MichaelHiller** [comment]
I computed the chains and in the locus with ENSDART00000127570 I get the same result as you did
![image](https://github.com/hillerlab/TOGA/assets/8644098/79182e95-b18c-4230-9872-1eb171d4e08c)


It is clear that zebrafish and pike are quite distantly related, as intronic / intergenic regions barely align. 

Can you pls send me the Zebrafish gene IDs for the genes that TOGA doesn't find? 
If you mean TLR19 (ENSDART00000132944), then this gene does not align on the top 2 chains that are syntenic. But there is a smaller chain from the same pike scaffold that aligns to pike NC_025987:16,932,881-16,935,145 and covers TLR19. This chain however only aligns coding exons, which is why TOGA likely will classify it as a paralog (it is trained to do that). But this chain could be the TLR19 ortholog. If so, there is likely a local rearrangement in this locus, as otherwise the smaller TLR19 aligning chain would be part of the top chain.

**Comment by liuxiaojieyx** [comment]
You are right. The gene is Tlr19, ID is ENSDART00000132944 & ENSDART00000179865 in Zfish. 
As I understand, if there is a chain that cover the gene and the exons quite well, then it's should be annotated. How comes TOGA can not identified the orthologs of this gene, but it did quite well with the genes surrounding this gene? 
"This chain however only aligns coding exons, which is why TOGA likely will classify it as a paralog (it is trained to do that)", I can not understand this sentense. Does it mean Tlr19 should be annotated as paralog based on the chain by TOGA? 
BTW, as you may notice from the first picture I posted, most of the annotation of Esox was coloured as brown, which means most of them are paralogs from the instruction of TOGA.
Then what should I do to make this gene annotated? Actually, this is my frist try for this analysis and I have quite a bit later.

**Comment by MichaelHiller** [comment]
"As I understand, if there is a chain that cover the gene and the exons quite well, then it's should be annotated. "
--> No, TOGA distinguishes between orthologs and paralogs. And in this case, where you use TOGA for evolutionary distances that the method is not designed for, the TLR19 chain looks like a paralog (both to TOGA as well as my trained eye). 
Pls have a look at Figure 1 in the TOGA paper to better understand how it works. 

yes, brown genes are cases, where TOGA does not find an orthologous chain, but only a chain classified as paralogous. If the query locus then has no orthologous gene, TOGA will annotate the gene, but label it is a potential paralog. We implemented this feature for cases where the real ortholog is missing. But in cases when TOGA is applied to large evo distances, this also helps annotating genes. 
--> In the TLR19 case, does TOGA annotate it as a brown gene (paralog)?

**Comment by liuxiaojieyx** [comment]
Hi, 
As indicated in the picture, the TLR19 is totally deleted based on the TOGA result. That is what I can not understand. Because the chain is there and the genes surrounding this gene are annotated as paralogs. If the TLR19 is annotated as paralogs, then it is totally no problem. What I can not understand is that TLR 19 is totally disappeared in this case.  
![image](https://github.com/hillerlab/TOGA/assets/148746834/2ed17f75-9dfc-4a23-9921-20aa196cec30)
![image](https://github.com/hillerlab/TOGA/assets/148746834/46739c5d-ffe2-41c5-9bef-b57e76ab180b)

**Comment by MichaelHiller** [comment]
Good point. The deletion is based on the orthologous chain, which is the top chain that covers the up/downstream gene. 
If TOGA would recognize the TLR19 chain as orthologous, it would annotate the gene correctly. But again, the method is not designed for such large evo distances. 

I have a suggestion. Could you use a reference species that is much closer to the pike? At a distance similar to human-mouse (or closer).

**Comment by liuxiaojieyx** [comment]
If I look into the output prot.fasta, there is no alignment between the reference and query genome. However, if I align the sequence of Zfish TLR19 and Pike TLR19 (from the genome annotation), then they aligned quite well. Do you think its because of the large variation betweene the introns and there is no synteny in the chain file?
I will take a try to use reference with close evolutionary relationship to annotate and see what happens. ![image](https://github.com/hillerlab/TOGA/assets/148746834/1a2a81ec-c5f6-4fbb-be33-b8417d09b280)
![image](https://github.com/hillerlab/TOGA/assets/148746834/48aa53c3-2172-49ce-8635-46afe35ac1e7)

**Comment by MichaelHiller** [comment]
>Do you think its because of the large variation betweene the introns and there is no synteny in the chain file?

Yes, that is what I tried to explain. 
Pls have a look at Fig S6
![image](https://github.com/hillerlab/TOGA/assets/8644098/30703b9d-168f-467c-812e-cc510db13148)
