### ISSUE TITLE
Specifying additional slurm options

### ISSUE THREAD

**Issue by mchaisso** [hillerlab/TOGA#12]
I would like to including additional slurm parameters in the nextflow config files, but am not sure how to do this. I need to specify a partition to run on: the -p part option for slurm sbatch calls.
This is probably my shortfall of nextflow parameters, but if some comments were added that gave an example of this it will make the transition from snakemake easier.

Thanks!
-Mark

**Comment by kirilenkobm** [comment]
Hi @mchaisso,

To specify a partition pls set the process.queue parameter, such as
process.queue = 'your_partition_name'

Best,
Bogdan
