### ISSUE TITLE
number of founded processed pseudogenes is different from anotation registred  

### ISSUE THREAD

**Issue by jesusdeivid** [hillerlab/TOGA#125]
Hi Dear,

I am taking advantage of the fact that TOGA also generates files of processed pseudogenes and would like to test it for analysis on different plant species. Still, first I have tested on Arabidopsis vs Arabidopsis (same species for reference and query). The output file for pseudogenes shows that there are approximately 200 processed pseudogenes found by TOGA, however, in the TAIR database and also in the GTF annotation used by me in this test, there are about 900 known processed pseudogenes. I cannot understand what could be wrong, since I expected to find a number close to what is indicated in the annotation. In addition, the position and header for each pseudogene in proc_pseudogenes.bed when being searched in the TAIR database, match there are CDS genes.

I used all the parameters by default.

sincerely

**Comment by MichaelHiller** [comment]
This is hard to say. We didn't develop TOGA to find processed pseudogenes. We also never benchmarked this. 
This is rather a byproduct, which might be useful but is likely not comprehensive. 
I think there are probably more sensitive processed pseudogene detection methods out there.
