### ISSUE TITLE
Does TOGA run on GPU ?

### ISSUE THREAD

**Issue by Abhishek7Nayak** [hillerlab/TOGA#13]
Can TOGA be run using GPU and does it support parallel running

**Comment by kirilenkobm** [comment]
Hi,

TOGA supports parallel running on CPU cluster/multi-CPU PC.
So far, it doesn't use GPU (maybe the next version will do it).

**Comment by Abhishek7Nayak** [comment]
Thank you for the reply.
I have just two nodes with 64gb RAM each and 12 threads. I would like to run TOGA in these two nodes where it can utilize the resources of both the nodes. Can you please help in doing this, as i am new to CPUclusters.

Thank you
