### ISSUE TITLE
Can I merge orthologsClassification.tsv of some species to compile an orthology table for the species

### ISSUE THREAD

**Issue by lnyawen** [hillerlab/TOGA#133]
Hello @MichaelHiller and @kirilenkobm ,

I would like to know if it is feasible to compile a table of gene families by merging orthologsClassification.tsv for certain species. I noticed that one of the TOGA result files is for ortholog gene inference. I have a number of species that are calculated TOGA with human as reference, then I can get results like this:
```
t_gene q_gene
geneA gorGor_ref541
geneA panTro_ref263
geneA rheMac_ref934
geneA calJac_ref883
geneA calJac_ref884
geneB1 gorGor_ref2241
geneB2 gorGor_ref2242
geneB1 panTro_ref24363
geneB2 panTro_ref24364
geneB1 rheMac_ref89934
geneB2 rheMac_ref89936
geneB1 calJac_ref83483
geneB1 calJac_ref83484
geneB2 calJac_ref83486
```
then the result I can collate as something of the form:
```
homSap           gorGor                             panTro                                  rheMac                              calJac
geneA            gorGor_ref541                      panTro_ref263                           rheMac_ref934                       calJac_ref883,calJac_ref884
geneB1,geneB2    gorGor_ref2241,gorGor_ref2242      panTro_ref24363,panTro_ref24364         rheMac_ref89934,rheMac_ref89936     calJac_ref83483,calJac_ref83484,calJac_ref83486
```
Then, we can use this orthology table to infer the expansion or contraction of gene families.

I'm wondering if this is feasible.

Thanks

Ningyawen

**Comment by MichaelHiller** [comment]
I think this is a good idea and should work. 
I would consider filtering for I or PI (or UL) genes to only count the number of genes per family that are likely intact. 

Important is likely that all species have high-quality genomes with few missing genes and few genes that are incorrectly called lost because of base errors. If some genomes are draft assemblies with many more missing genes (that TOGA would recognize but label as missing), then Cafe may consider this to be a family contraction.

**Comment by lnyawen** [comment]
I have written a script and gotten some results. The idea of the script is as follows:
I selected a number of species and then based on orthologsClassification.tsv for each species, we will get the results like:

```
geneA gorGor_ref541
geneA panTro_ref263
geneA rheMac_ref934
geneA calJac_ref883
geneA calJac_ref884
geneB1 gorGor_ref2241
geneB2 gorGor_ref2242
geneB1 panTro_ref24363
geneB2 panTro_ref24364
geneB1 rheMac_ref89934
geneB2 rheMac_ref89936
geneB1 calJac_ref83483
geneB1 calJac_ref83484
geneB2 calJac_ref83486
```
Then based on the orthology relationship, we connect `t_gene` and `q_gene` with orthology relationship with a virtual line, such as 
```
geneA---gorGor_ref541---panTro_ref263---rheMac_ref934---calJac_ref883---calJac_ref884
geneB1---geneB2---gorGor_ref2241---gorGor_ref2242---panTro_ref24363---panTro_ref24364---rheMac_ref89934---rheMac_ref89936---calJac_ref83483---calJac_ref83484---calJac_ref83486
```
If a missing gene is encountered, `ENSG00000279761 ENST00000623930.OR5D13  None  one2zero`, then leave it alone. Then, these genes will be clustered into classes according to homology, and a class is a gene family. Then, we will organise the classes by species name and get a table of orthology table.

I hope I made that clear.

It seems I didn't take into account what you said about UL and PI. So let me consider the case where the gene is UL/PI, then it should work. What do you think?

**Comment by MichaelHiller** [comment]
Looks good to me. 
If you want to include UL and PI, you could first make a whitelist of genes or remove all others from the orthology file. 
With high-quality genomes, however, this should not be a major issue. 

In any case, I would carefully look at the Cafe output. We have seen cases where we can't see expansions or contractions, or they rather occurred in other branches.

**Comment by lnyawen** [comment]
OK, thank you very much! Thank you for your advice.
