### ISSUE TITLE
ValueError: Error! There are 57105 transcripts in the bed file absent in the isoforms file! There are the transcripts (first 100)

### ISSUE THREAD

**Issue by vinitamehlawat** [hillerlab/TOGA#134]
Hi Authors,
I ran TOGA with following command: `./toga.py /home/vlamba/New-gene-Noto/DisMaw-to-CotGob.chain /home/vlamba/12_GCF_900634415.1_fCotGob3.1.ensGene.bed /home/vlamba/New-gene-Noto/CotGob.2bit /home/vlamba/New-gene-Noto/DisMaw.2bit -i /home/vlamba/CotGob-isoform.txt --project_dir /home/vlamba/3_Noto-gene-loss --kt --cb 10,100 --cjn 500 --ms`

I got following error:
`
## Initiating TOGA class ##
# python interpreter path: /share/apps/python/anaconda-3.8/bin/python3
# python interpreter version: 3.9.6 (default, Aug 18 2021, 19:38:01) 
[GCC 7.5.0]
Version 1.1.7.dev
Commit: 65957c31430e380f0748cfa39e4a70b841b3cf0f
Branch: master

Python package versions
* twobitreader: 3.1.7
* networkx: 3.2.1
* pandas: 2.1.2
* numpy: 1.26.1
* xgboost: 2.0.1
* scikit-learn: 1.3.2
* joblib: 1.3.2
* h5py: 3.10.0
Calling cmd:
/scrfs/storage/vlamba/home/TOGA/./modules/chain_score_filter /home/vlamba/New-gene-Noto/DisMaw-to-CotGob.chain 15000 > /home/vlamba/3_Noto-gene-loss/temp/genome_alignment.chain

Command finished with exit code 0.

filter_bed: transcript ENSCGOT00000027906.1 skipped: no CDS
filter_bed: transcript ENSCGOT00000027984.1 skipped: no CDS
filter_bed: transcript ENSCGOT00000028036.1 skipped: no CDS
filter_bed: transcript ENSCGOT00000034499.1 skipped: no CDS
filter_bed: transcript ENSCGOT00000039655.1 skipped: no CDS
Traceback (most recent call last):
  File "/scrfs/storage/vlamba/home/TOGA/./toga.py", line 1742, in <module>
    main()
  File "/scrfs/storage/vlamba/home/TOGA/./toga.py", line 1737, in main
    toga_manager = Toga(args)
  File "/scrfs/storage/vlamba/home/TOGA/./toga.py", line 260, in __init__
    self.__check_param_files()
  File "/scrfs/storage/vlamba/home/TOGA/./toga.py", line 362, in __check_param_files
    self.isoforms = check_isoforms_file(self.isoforms_arg, t_in_bed, self.temp_wd)
  File "/scrfs/storage/vlamba/home/TOGA/modules/sanity_check_functions.py", line 136, in check_isoforms_file
    raise ValueError(err_msg)
ValueError: Error! There are 57105 transcripts in the bed file absent in the isoforms file! There are the transcripts (first 100):
ENSCGOT00000006356.1
ENSCGOT00000031666.1
ENSCGOT00000028180.1

#Without isofrom.txt TOGA is running# 

`Here is my isofrom.txt file:`
Gene_ID	Transcript_ID
ENSCGOG00000000002	ENSCGOT00000000002
ENSCGOG00000000002	ENSCGOT00000000003

`head -n 5 of is  .bed  file:`
NC_041355.1	3914	21966	ENSCGOT00000000002.1	0	+	5778	19754	12,12,120	25	760,133,102,73,62,45,182,49,120,129,159,183,139,182,157,164,135,184,107,195,169,135,160,97,2359,	0,1857,2239,3080,3239,3386,3533,3913,4053,4807,7222,7825,8575,9762,10157,10945,11201,11746,12172,12657,13205,13753,14173,15130,15693, 

I would really appriciate any help or suggestion from your end.

Thank you very much

**Comment by vinitamehlawat** [comment]
Hi Authors, I figured out this problem and was able to resolve the issue.

Thank you! for sharing this amazing tool.

**Comment by MichaelHiller** [comment]
Great to hear. If the fix could be relevant for others having the same problem, pls share how you fixed it. 
Thx

**Comment by vinitamehlawat** [comment]
Hi Dr. @MichaelHiller 

I just realised that in my bed file all the transcripts are with .1 extension in every transcript ids: for example in bed file I have `ENSCGOT00000006356.1` but in isoform file the same id was like this `ENSCGOT00000006356`. So I put `.1` in every transcript id in isoform and it worked for me.

Thank you
