### ISSUE TITLE
question about bigmem job

### ISSUE THREAD

**Issue by lizihe21** [hillerlab/TOGA#14]
Hi, I've just update the TOGA and found the new parameter --cesar_bigmem_config. It is confusing what these bigmem jobs are. Are they the jobs that require more memory than --cesar_mem_limit?

**Comment by kirilenkobm** [comment]
Hi,

Exactly, some CESAR jobs might require 100, 200, 500, or even more GB of RAM.
If each node on your cluster has 1Tb+ of RAM, then it should be no problem, just set --cb option to something like 8,16,32,64,128,256,512,1000. Most likely, no jobs will require > 1Tb.

However, it could be useful for clusters with several partitions of nodes.
For example, 2000 cores on nodes with 256Gb of RAM and a couple of 1Tb nodes.
Then it would be most optimal to run ordinary CESAR jobs on 256 Gb nodes and push heavier jobs to 1Tb partition. To do so, the user may create an alternative config file for big men jobs.

**Comment by lizihe21** [comment]
Thanks for quickly responding. My cluster system has two kinds of nodes with 5g and 20g mem per cpu. Though I still don't know what is the threshold about the big mem nodes, I have inserted some determination about the --cb value to finish the pipeline.
best.

**Comment by Abhishek7Nayak** [comment]
@lizihe21 
Hello I have two nodes with 64GB of RAM and 12 threads , and i dont know how to use both of the nodes and run TOGA using nextflow. Can you please me in running TOGA using cluster system.

Thank you

**Comment by kirilenkobm** [comment]
Pls reopen the issue is the problem is still relevant.
