### ISSUE TITLE
duplicate transcript names in query_annotation.bed

### ISSUE THREAD

**Issue by fuesseler** [hillerlab/TOGA#147]
Hello,
Thanks for developing this great tool!

When trying to use the TOGA query_annotation.bed for some downstream applications I noticed something strange:

There are three transcript names (ENSACAT00000051202.-1 ; ENSACAT00000056716.-1 ; ENSACAT00000043444.-1 ) that are duplicated in my query_annotation.bed file. I extracted these from the .bed to show them below:

> h1tg000023l	12206043	12206104	ENSACAT00000051202.-1	1000	-	12206043	12206104	255,160,120	1	61,	0,
> h1tg000023l	12192278	12192490	ENSACAT00000051202.-1	1000	-	12192278	12192490	255,160,120	1	212,	0,
> h1tg000004l	233822694	233822837	ENSACAT00000056716.-1	1000	+	233822694	233822837	0,200,255	1	143,	0,
> h1tg000004l	3782971	3806116	ENSACAT00000056716.-1	1000	+	3782971	3806116	0,200,255	16	108,188,201,120,184,78,104,97,67,164,97,225,137,115,162,58,	0,2486,3658,5235,7943,8530,9615,10766,11832,13890,16216,18117,19382,20200,22228,23087,
> h1tg000009l	3478410	3478430	ENSACAT00000043444.-1	1000	-	3478410	3478430	0,200,255	1	20,	0,
> h1tg000004l	3782971	3806116	ENSACAT00000043444.-1	1000	+	3782971	3806116	0,200,255	16	108,188,201,120,184,78,104,97,67,164,97,225,137,115,162,58,	0,2486,3658,5235,7943,8530,9615,10766,11832,13890,16216,18117,19382,20200,22228,23087,

I am not sure if this behavior is normal? From my understanding, I would expect only unique IDs in this file.
Also, I am curious about the meaning of the ."-1" at the end  of the transcript names - does a positive vs a negative number hold any special meaning?

Best regards,
Flora

**Comment by MichaelHiller** [comment]
For ENSACAT00000051202 and ENSACAT00000043444 you get 2 distinct query loci. If you grep these from the orthology file, you likely get a 1:many relationship. TOGA likely finds here 2 co-orthologs. 

-1 instead of a proper chainID indicates that gene was split across 2+ scaffolds in your genome. TOGA by default recognizes orthologous fragments and stitches them together (e.g. fig below). 
In a new version, we will comma-list the chain IDs instead of -1. 
![image](https://github.com/hillerlab/TOGA/assets/8644098/3c4735c8-584e-4940-809f-9390e32df914)

**Comment by fuesseler** [comment]
> For ENSACAT00000051202 and ENSACAT00000043444 you get 2 distinct query loci. If you grep these from the orthology file, you likely get a 1:many relationship. TOGA likely finds here 2 co-orthologs.
I checked, and they are many2one and many2many, respectively. 

My main issue is, that I am trying to use the annotation_query.bed results for improvement of my genome annotation, and the software I'm trying to use for integration with other evidence (TSEBRA) is throwing the error that the Transcript ID is not unique for the above cases.

So for now, it's probably easiest if I filter these loci out from the .bed file to be able to continue.
But from what I understand, in the future with a comma-listed chainID this will not be an issue anymore, as that way the transcript IDs will be unique?

**Comment by MichaelHiller** [comment]
OK, I now undestand the problem. The projection name (transcript.gene.chainID) is unique, unless you the transcript had two loci where it was broken between scaffolds (like ENSACAT00000043444.-1 ). 

I would use an awk command to print all fields and add $4","NR 
to the projection name (giving each ,lineNumber), which makes it unique. 

Yes, comma-listed chainID will make it unique in future.

**Comment by fuesseler** [comment]
Thanks! This clears the behavior up for me. 

The awk command works, but I would have to do some extra work on updating the query_isoforms.tsv file correspondingly (as I need it for using it for bed2gtf). But I will figure this out.

Thank you for the insightful answers and help! I will close the issue now.
