### ISSUE TITLE
Non-unique transcript names assigned to invalid chain IDs

### ISSUE THREAD

**Issue by ning-y** [hillerlab/TOGA#153]
I found the following two entries in a `query_annotation.bed` output from (version "TOGA 1.1.7.dev", commit https://github.com/hillerlab/TOGA/commit/98ec464b0ebec5f715e6bfb6d7d92a4684eb240b).

```bash
$ grep "ENST00000539924.5.-1" query_annotation.bed
s1      158748435       158757526       ENST00000539924.5.-1    1000    -       158748435       158757526       0,0,200 9       213,204,102,105,188,163,241,161,93,     0,962,1546,2035,5150,5652,6109,8286,8998,
s1      158717209       158717293       ENST00000539924.5.-1    1000    -       158717209       158717293       0,0,200 1       84,     0,
```

Exploring further: in total, there are 131 such entries assigned to chain "-1", and they span many different chromosomes.

```bash
$ grep -P '.-1\t' query_annotation.bed | wc -l
131
$ grep -P '.-1\t' query_annotation.bed | cut -f1 | sort | uniq | wc -l
13
```

I created the chain using make_lastz_chains (commit https://github.com/hillerlab/make_lastz_chains/commit/187e313). There is no chain with an ID of "-1".

```bash
$ zcat chain.gz | grep chain | head -n 5
chain 3359782070 chr6 170805979 + 28518742 170587161 s2 188430977 + 88711387 188358544 1
chain 2966506772 chr2 242193529 + 121810722 241879088 s1 181250738 - 90576796 181165539 2
chain 2700997074 chr5 181538259 + 7921846 129325056 s8 112366244 - 905294 82451540 3
chain 2475567646 chrX 156040895 + 284156 155945946 s10 112226977 - 48346 107056278 4
chain 2418919274 chr1 248956422 + 907682 94823350 s2 188430977 + 122314 66711976 5
$ zcat chain.gz | grep chain | grep '\-1'
[empty output]
```

This creates a tricky situation where entries in the BED file cannot be mapped to information from other TOGA outputs e.g. orthology scores.

```bash
$ grep "ENST00000539924.5" orthology_scores.tsv 
ENST00000539924.5       187399  0.0041570886969566345
ENST00000539924.5       247552  0.0041570886969566345
ENST00000539924.5       922379  0.0041570886969566345
ENST00000539924.5       981     0.9884904623031616
ENST00000539924.5       15305   0.895673930644989
ENST00000539924.5       44      -1.0
ENST00000539924.5       7       -1.0
```

I've checked TOGA outputs from mapping human to other species, and this issue occurs in all that I have checked (13 out of 13 other TOGA runs with the same versions of make_lastz_chain and TOGA).

**Comment by ning-y** [comment]
A fix may not be necessary, if these transcripts ending in "-1" can be safely ignored e.g. if they correspond to the minimum possible orthology score. So, I would like to ask firstly if these transcripts ending in "-1" can be safely ignored. :blush:

**Comment by MichaelHiller** [comment]
Nope, -1 indicates that the gene was assembled from several chains (see Fig 4 in the TOGA paper and the supplement). 
So these are genes which are separated on different scaffolds in your assembly. TOGA recognizes the orthologous parts and puts them together.

The orthology_scores.tsv will then contain the probs of the individual chains. 

What we will improve in the next major TOGA release is writing the chainIDs that were put together in a comma-separated list, instead of writing -1. This then preserves the info which chains where used.

**Comment by ning-y** [comment]
@MichaelHiller I understand it now, thank you!

So, if I am annotating bat with human: if there are two different bat transcripts matching the same one human transcript, but both bat transcripts are assembled from several chains (both are suffixed with ".-1"), then it is impossible to tell in this current version which has better orthology score e.g. by mean orthology score of chains contributing to that assembled transcript?

**Comment by MichaelHiller** [comment]
If I understand you right, there are two loci in your query genome where the same human transcript gets mapped to with -1 as the chain ID. In this case, you likely have an incomplete assembly and one half of the transcript maps to one scaffold and the other half maps to another scaffold. 
In the bed file, you can see how many exons do the 2 transcript parts contain. 
In your case
s1      158748435       158757526       has 9 exons and 
s1      158717209       158717293    has 1 exon. 
The 2 chains corresponding to the 2 scaffolds are 
ENST00000539924.5       981     0.9884904623031616
ENST00000539924.5       15305   0.895673930644989
and both have high probabilities. Likely 15305 corresponds to the 1-exon locus.
