### ISSUE TITLE
The question of inactivate mutation identification

### ISSUE THREAD

**Issue by txfc** [hillerlab/TOGA#163]
Hello, I've successfully run the TOGA pipeline, but I'm still unclear about inactivate mutation identification.
I use chicken as a reference genome to apply to other birds. This is the inact_mut_data.txt of the output file.
I noted this gene XXX lost the start code at the beginning of ORF, but TOGA did not identify the mutation as an inactivating mutation. Does this mutation have little effect on gene function?
```
GENE: XXX
# XXX    24      1       1       START_MISSING   ---     masked  START_1
# XXX    24      3       66      ATG     GTG->ATG        masked  ATG_1
# XXX    24      3       91      FS_DEL  -1      unmasked        FS_1
# XXX    24      4       109     ATG     ATG->ATG        masked  ATG_2
# XXX    24      4       110     ATG     ATG->ATG        masked  ATG_3
# XXX    24      4       140     FS_DEL  -1      masked  FS_2
# XXX    24      INTACT_PERC_IGNORE_M 0.5448275862068965
# XXX    24      INTACT_PERC_INTACT_M 0.5448275862068965
# XXX    24      INTACT_CODONS_PROP 0.903448275862069
# XXX    24      OUT_OF_CHAIN_PROP 0.0
# XXX    24      MIDDLE_IS_INTACT FALSE
# XXX    24      MIDDLE_IS_PRESENT TRUE
```
And then I get a plot about the gene XXX by plot_mutation.py. 
![image](https://github.com/hillerlab/TOGA/assets/110294553/2addddb7-5b9d-4beb-b0b8-00bbd96f6829)
Why doesn't the plot show the deletion (START_MISSING) in the first exon? 
This is the alignment result of the gene.
```
>XXX
------------------------------ACAGAGCGTACCTGCAAGCAGCTGGACTTACTTCCTCTGAAATGTGATGCATGTAGGGAAGCCTTCTGGAAAGATCACAGCTGTTACGGTGACCACAAGTGTAGCTCTGCCTACAAGGAAAATGTGCAGGTTCTAGTGTGTCCACTCTTCAGTGCACTTGTCCTAATGCAGAAGGGGGAAATACCAGAT---GTGGTTGGAGCTCACATAGATAAGCACTGCAAACACAATCCAGCACAAAA-AAGAAGAGCATCTTCACAAGCAAGTGCTTAAAG------TGCAAAAGGAAAGAGATGATGAAGGTAGTTTGTGACCAGTGCAGTGGCAACTTCTGCATAAAACATCGACGGCCTCCGGGTCACGACTGTAAAGGGAGCAGCCACCCAA-CTCCAAGGCAGGGTAA

```

I also have another question about the color in the plot_mutation.py. What is the difference between the blue and red?
![image](https://github.com/hillerlab/TOGA/assets/110294553/8fc439be-f284-4ff0-aa52-c3811c45ac9b)
The first four exons of this gene have del mutation. Why the first three exons are blue, but the fourth exon is red.
This is the inact_mut_data.txt of the output file. The mutation in the fourth exon is not masked.  What is different about the first three exons?
```
GENE: AAA
# AAA  23      1       0       Deleted exon    -       masked  DEL_1
# AAA  23      2       0       Deleted exon    -       masked  DEL_2
# AAA  23      3       0       Deleted exon    -       masked  DEL_3
# AAA  23      4       0       Deleted exon    -       unmasked        DEL_4
# AAA  23      5       148     ATG     ATG->ATG        masked  ATG_2
# AAA  23      5       149     COMPENSATION    FS_2-3  unmasked        C_1
# AAA  23      5       149     FS_DEL  -2      masked  FS_2
# AAA  23      5       155     FS_DEL  -1      masked  FS_3
# AAA  23      INTACT_PERC_IGNORE_M 0.1534090909090909
# AAA  23      INTACT_PERC_INTACT_M 0.1534090909090909
# AAA  23      INTACT_CODONS_PROP 0.1534090909090909
# AAA  23      OUT_OF_CHAIN_PROP 0.0
# AAA  23      MIDDLE_IS_INTACT FALSE
# AAA  23      MIDDLE_IS_PRESENT TRUE

```
Looking forward to your reply. I will appreciate it very much.

Best ragards!

**Comment by txfc** [comment]
Excuse me, what is the problem with my question description? could you please help me to understand this question? @MichaelHiller @kirilenkobm  Thank you very much.

**Comment by MichaelHiller** [comment]
Hi, 

TOGA does not treat a missing start codon as an inactivating mutation. The reason is that often (but not always) there is another ATG in frame not so far away. 
In your case, it looks like the first coding part is deleted (or overlaps an assembly gap). 
The two other frameshifts you find in this XXX gene have nothing to do with the missing part. 
Overall, this gene is likely lost. 

Wrt your second question. The TOGA html contains this information right underneath the plot
![image](https://github.com/hillerlab/TOGA/assets/8644098/38a7b76a-1bed-4098-9ea2-ed48eb340664)
Since at least one exon deletion shifts the reading frame, TOGA treats that as an inactivating mutation. 

Best
Michael

**Comment by txfc** [comment]
Thank you, I have understood it.
