### ISSUE TITLE
Operational problems with CESAR2.0

### ISSUE THREAD

**Issue by molinfzlvvv** [hillerlab/TOGA#165]
Hi! Authors

I seem to be in a bind, I can't submit the task to the slurm system during the CESAR alignment. So I currently only have a local node with 40 cores, but in the actual running process I found that it only takes up two cpus. The reason may be that I only split into two buckets based on memory(--cesar_buckets 10,100). Even if I changed the process.cpus = 1 to 40 in the call_cesar_config_template.nf file, it still only takes up a small amount of CPU. It has been running for nearly a week now. I would appreciate it if you have any parameters or settings to speed it up.

my command :
./toga.py hg38.Ju.final.chain ./TOGAInput/human_hg38/toga.transcripts.bed ./hg38.2bit ./Judaei.2bit --kt --pn ./gene_loss/Judaei -i ./TOGAInput/human_hg38/toga.isoforms.tsv --nc /home/fengzl22/TOGA/nextflow_config_files --cb 10,100 --cjn 500 --u12 ./TOGAInput/human_hg38/toga.U12introns.tsv --ms

the log:
Polling iteration 8545; already waiting 512700 seconds.
Polling iteration 8546; already waiting 512760 seconds.
Polling iteration 8547; already waiting 512820 seconds.
Polling iteration 8548; already waiting 512880 seconds.

Looking forward for your reply, it will help me a lot.

Best regards!

**Comment by MichaelHiller** [comment]
Hi, 
there is no multithreading in CESAR, meaning you can only parallelize over the mem queues provided or by installing say Slurm to use your server as a cluster. 
If there is no larger compute cluster available, I would try the latter option. Alternatively, maybe try to create more memory queues to parallelize. 

We are working on a faster and less memory demanding TOGA version, which can hopefully be released soon.
