### ISSUE TITLE
TOGA annotation of sex chromosomes

### ISSUE THREAD

**Issue by smorzechowski** [hillerlab/TOGA#167]
Hello! I have a question about how TOGA handles the annotation of sex chromosomes that have recently diverged, and possess gametologs (Z-linked and W-linked copies) that are similar to each other. If a particular gene exists on both Z and W scaffolds, for instance, is there any reason to expect that TOGA would have trouble annotating these as two different copies (i.e. gametologs) of the same gene? I'm particularly interested in differentiating genes with both gametologs from genes where the W gametolog has been lost or is now a pseudogene due to sex chromosome degeneration. 

If TOGA categorizes gene transcripts as **Lost** or **Uncertain Loss** on W scaffolds, but **Intact** on Z scaffolds, then can I safely assume that the W-linked version is indeed accumulating inactivating mutations? I assume so, but I just wanted to double check.

I am pleased at how well TOGA has worked on the non-model avian species I am studying, many thanks for the great tool!

**Comment by MichaelHiller** [comment]
Hi, 

although I never looked into this, I would assume if the reference has a single gene and your query species has a recently emerged Z and W chromosome (where the gene's locus is assembled well in both locations), then TOGA should infer a 1:2 orthology relationship, as this would look like a locus duplication in the query. Those genes should not be harder to annotate. 

Each orthologous locus (on W or Z) would be independently classified as Intact, Lost, Uncertain Loss etc. So if W is lost and Z is intact, then can believe that :-)

A note: If the W copy is classified as lost and Z is intact, the TOGA would infer a 1:1 orthology relationship (similar to Fig 1H in the paper). 

Happy to hear that the method seem to work

**Comment by smorzechowski** [comment]
Thanks very much for the quick and helpful response, that makes sense! Much appreciated :)
