### ISSUE TITLE
run with multiple query genomes

### ISSUE THREAD

**Issue by philge** [hillerlab/TOGA#172]
Hi,

if we provide Genome alignment between the reference and query genome(s), wont Toga annotate each query genome and give the output? In that case will it be faster than running say 10 query genomes separately?

Thanks,
Philge

**Comment by MichaelHiller** [comment]
TOGA is strictly pairwise. This is what the method was implemented for. If you have 1 ref aligned to 10 queries, then pls run it 10 times in parallel.
