### ISSUE TITLE
support for transferring miRNA annotations?

### ISSUE THREAD

**Issue by lichennan123** [hillerlab/TOGA#173]
Hello!

I have been using TOGA lately for transferring hg38 gene annotations to a newly constructed genome and it looks good so far! However, I do notice that annotations for non-coding RNAs such as miRNAs are not applied to my query genome at all, even though my reference genome contains this information and the isoform.txt input includes ensembl gene/transcript ids for every gene type. Do you have any thought about why this might be an issue and what I can do to allow these annotations be transferred? I'd appreciate your advice! Let me know if additional details are needed.

Sincerely,
Chennan

**Comment by MichaelHiller** [comment]
Right now, TOGA can only handle coding genes, because CESAR is a codon-aware aligner. 
We don't have a TOGA version that can project non-coding genes. 

If you want to do some coding, you could do the following: For miRNAs that are close to genes or intronic, you could use the aligning miRNA coordinates of the orthologous chain to annotate them in the query.

**Comment by lichennan123** [comment]
This is very helpful - thank you!

**Comment by xfyhy** [comment]
> Right now, TOGA can only handle coding genes, because CESAR is a codon-aware aligner. We don't have a TOGA version that can project non-coding genes.
> 
> If you want to do some coding, you could do the following: For miRNAs that are close to genes or intronic, you could use the aligning miRNA coordinates of the orthologous chain to annotate them in the query.

Pardon me for hitchhiking.
@MichaelHiller  you suggested using chain file to map different genome coordinates. I noticed that liftOver can map different genome versions of the same species, but what software should be used for cross-species. - thank you!

**Comment by MichaelHiller** [comment]
Right, liftOver requires chains such that each base in the reference overlaps at most 1 chain (they are computed by back-converting nets to chains). 
Liftover can also work. 
But for miRNAs close to genes, TOGA's orthology calls (which chains represent orthologs for this gene) could be useful as well. Something that needs to be explored and benchmarked
