### ISSUE TITLE
Script to convert gtf file to TOGA input

### ISSUE THREAD

**Issue by DustinSokolowski** [hillerlab/TOGA#177]
Hello!

Thank you for this fantastic annotation tool. I was hoping to use TOGA to annotate my rodent but using a more closely related reference species than mmus, as I imagine it would have higher alignments and thereby annotations assuming a similar genome quality (E.g. ENSEMBL stable release). I was wondering if there is a script to convert a gtf/gff file to the multiple input files needed for a TOGA reference species? If not I can go about writing one which I can send your way (if you'd like).

Best,
Dustin

**Comment by MichaelHiller** [comment]
UCSC's kent source provides gtfToBed and gff3ToBed. This has worked for us well in the past.
