### ISSUE TITLE
Treatment of different gene sets

### ISSUE THREAD

**Issue by molinfzlvvv** [hillerlab/TOGA#178]
Hi, authors

I have successfully completed the TOGA process for several species. I wanted to focus on the differences between species, so I screened the "L" gene sets and analyzed the specific loss, but unfortunately I could not find any valuable pathways. What other work can I do in this case, such as expanding the lost genes to the UL set, and how can I correctly recognize and deal with the remaining sets (I, PI, M, PM)

This puzzled me a lot.Looking forward to your reply.

**Comment by MichaelHiller** [comment]
Yes, include UL cases. 
If your genome is really complete, you can also include M, but pls carefully validate all putative gene losses
