### ISSUE TITLE
TOGA as a tool to age genes?

### ISSUE THREAD

**Issue by DiegoSafian** [hillerlab/TOGA#179]
Hi,

I am wondering whether TOGA can also be used to estimate gene age (when different genes appeared in the tree).  I know gene_age-dating pipeline (https://github.com/Zhanglab-IOZ/SBP_age-dating/blob/master/pipeline.md) from Zhang lab. uses similar alignment steps and resources to estimate gene age based on genome alignment and so on. 

Kind regards,
Diego

**Comment by MichaelHiller** [comment]
You mean finding the branch in the phylogenetic tree where the gene originated? 
E.g. finding a gene conserved between human and rodents/lagomorphs but not outside Euarchontoglires, one can infer that it originated in the Euarchontoglire ancestor. 
This could work, however keep in mind that TOGA is developed for species that are 'alignable'. So if TOGA does not find an ortholog for a human gene in birds does not mean that the gene originated in mammals. Over larger distances, an ortholog may exist but TOGA may not detect it, as it is not designed for larger distances.

**Comment by DiegoSafian** [comment]
Thanks for your answer.

yes, that is exactly what I meant. Would you say that this would work in species that diverged less than 60 mya?

**Comment by MichaelHiller** [comment]
60 My between nematodes will be like human-mouse in molecular distance. 
A better metric would be ~0.6 or less subs per neutral sites in the genome.
