### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 1 with size 0

### ISSUE THREAD

**Issue by Huangyizhong** [hillerlab/TOGA#18]
Hi, there

 I want to use the TOGA to do gene prediction. When I runned the test data as follows: ./run_test.sh micro
The three steps worked well. There have some problems in the final steps .
#### STEP 4: Classify chains using gradient boosting model

Decision tree in progress...
Loading dataset...

Load and apply model

Traceback (most recent call last):
  File "./toga.py", line 1270, in <module>
    main()
  File "./toga.py", line 1266, in main
    toga_manager.run()
  File "./toga.py", line 572, in run
    self.__classify_chains()
  File "./toga.py", line 726, in __classify_chains
    annot_threshold=self.orth_score_threshold)
  File "/home/goldenpigs217/softwares/TOGA/modules/classify_chains.py", line 134, in classify_chains
    se_pred = se_model.predict_proba(X_se)[:, 1]
IndexError: index 1 is out of bounds for axis 1 with size 0
My python is  3.6.5.
 Need your help!
Thanks advances!
Yizhong Huang

**Comment by kirilenkobm** [comment]
Hi Yizhong,

thanks for a good catch.
Have no idea why earlier pandas versions didn't crash at this point.
This is fixed now.

Best,
Bogdan
