### ISSUE TITLE
Exon related statistics

### ISSUE THREAD

**Issue by wang748** [hillerlab/TOGA#180]
Dear developer, I would like to know if toga can predict the exon addition and deletion in the query sequence relative to the reference sequence?

**Comment by MichaelHiller** [comment]
Exon deletions, yes. Those will be treated as an inactivating mutation if the deletion would introduce a frameshift. 

Exon additions (novel exons in the query or exons lost or not annotated in the reference), no.

**Comment by wang748** [comment]
Through the result file "inact_mut_data.txt", I found that "Missing" and "Deleted" appeared in some lines of the fifth column, and "exon" was displayed in the sixth column of these lines. So are the genes represented by these lines the genes with exons missing?

**Comment by MichaelHiller** [comment]
Missing means we couldn't find the exon because there is an assembly gap in the expected locus. 
Deleted is either deleted or aligned below our thresholds, in which case we infer that the exon is no longer present in the genome. Only deleted will be relevant for you.
