### ISSUE TITLE
Error with CESAR_wrapper.py: realign_exon _ ValueError: too many values to unpack 

### ISSUE THREAD

**Issue by vpymerel** [hillerlab/TOGA#185]
Hello !

I got the following error when running toga:

!!Traceback (most recent call last):   File "/beegfs/home/merel/TOGA/CESAR_wrapper.py", line 2661, in <module>     realign_exons(cmd_args)   File "/beegfs/home/merel/TOGA/CESAR_wrapper.py", line 2358, in realign_exons     search_locus, subch_locus, chain_data = chain_cut(                                             ^^^^^^^^^^   File "/beegfs/home/merel/TOGA/CESAR_wrapper.py", line 644, in chain_cut     search_region_shift_str = range_corrector(                               ^^^^^^^^^^^^^^^^   File "/beegfs/home/merel/TOGA/CESAR_wrapper.py", line 580, in range_corrector     chrom, start_end = g_range.split(":")     ^^^^^^^^^^^^^^^^ ValueError: too many values to unpack (expected 2)

Do you what it means ? And what it could represent ?

thank you,
Vincent

**Comment by MichaelHiller** [comment]
@kirilenkobm Bogdan, have you seen this error before? Doesn't mean anything to me.

**Comment by vpymerel** [comment]
My bad, it seems to be due to scaffold with ":" and/or "-" in their names,

I am closing the issue,

Thank you !
