### ISSUE TITLE
Do you recommend to improve the annotation of an existing genome with TOGA?

### ISSUE THREAD

**Issue by MauriAndresMU1313** [hillerlab/TOGA#188]
Hi, I would like to ask for your opinion on my strategy and see if it is possible at all.  

Currently, I'm trying to improve the annotation of unknown genes in my transcriptomic data from a mammal that has a reference genome available.

I read the paper related to TOGA, and it seems like I can use this tool to improve annotation using related species, for example, mammals that belong to the same family as my main species.

Is TOGA suitable for this task, or is it not a good idea? 

Any comment is more than welcome and appreciated!

**Comment by MichaelHiller** [comment]
If I understand it correctly, you have a transcriptome based gene annotation, but often not a proper gene symbol (unknown gene). Meaning you don't know which gene it is (what the ortholog is in other species).

Yes, then TOGA can help. If a TOGA transcript (CDS only) overlaps a transcript from your annotation on the same strand, then this tells you which gene it is. 

Let me know if I got this right

**Comment by MauriAndresMU1313** [comment]
Thank you for your quick response! I have RNA seq data from ferret, for example, I have like 25 % of unknown gene symbols on average. So my idea was to improve this annotation, looking for orthologs genes from related species, and if related species fails to improve the annotation, use humans or mice. So looks like based on your answer it is possible, am I right?

**Comment by MichaelHiller** [comment]
Yes, maybe you both human and mouse as a reference. 
We have TOGA runs for several ferret genomes on our download page I think

**Comment by MauriAndresMU1313** [comment]
Great!, could you provide that link?

**Comment by MichaelHiller** [comment]
https://genome.senckenberg.de/download/TOGA/
https://genome.senckenberg.de/
