### ISSUE TITLE
Getting 5' UTR of a gene from TOGA orthologs

### ISSUE THREAD

**Issue by cakeinspace** [hillerlab/TOGA#189]
Thanks for the tool. I wanted to ask if it's possible to get the 5' UTR of the orthologs computed or is that something that can't be done in the absence of transcript data for some species. One way I can think of is by finding the location of the query gene in the scaffold or assembled genome and then taking lets say 50-100 bp (assuming that the length of the 5' UTR in the reference genome is this) upstream of the query gene.

Thanks

**Comment by MichaelHiller** [comment]
TOGA 1 generates annotations that only have CDS, but in the upcoming TOGA 2.0 we will also predict UTRs based on aligned regions. This seems to work surprisingly well. 
We think we can release TOGA 2 in a few weeks. This will happen in a new repository, likely https://github.com/hillerlab/TOGA2

**Comment by vpymerel** [comment]
Hello,

May I ask for an update on this question ? Some of my project would greatly benefit from toga based UTRs prediction ;-)

Thank you again for the tool !
Vincent

**Comment by MichaelHiller** [comment]
Thx for the ping.
@ReverendCasy will release TOGA2 with a fast UTR addition script (works quite well overall, though some predicted UTR differ substantially from transcriptome-based UTRs) this week. Likely Wed. 
Pls watch for https://github.com/hillerlab/TOGA2
