### ISSUE TITLE
My loss_summ_data.tsv contains UL, What does that mean?

### ISSUE THREAD

**Issue by Abhishek7Nayak** [hillerlab/TOGA#19]
Many of my projected transcripts have been classified as UL. Does that mean the projected transcript has lost?

Thank you

**Comment by Abhishek7Nayak** [comment]
I got it thank you!!

**Comment by yuzhenpeng** [comment]
> Many of my projected transcripts have been classified as UL. Does that mean the projected transcript has lost?
> 
> Thank you

Hi, could you mind tell me what mean of classified UL for transcripts.

**Comment by Abhishek7Nayak** [comment]
@yuzhenpeng 
It means uncertainly lost. If 49 % of CDS is not conserved, then that particular gene is classified as UL.
