### ISSUE TITLE
the number of U12 

### ISSUE THREAD

**Issue by Alisa-1-lgtm** [hillerlab/TOGA#190]
Hello!
I counted the number of U12 introns in supply/hg38.U12sites.tsv, and it's over 2871. But in U12DB and IAOD, even generated by intronIC, the number of U12 introns  is much less than 2000(only about 600).So, i want to know  that is why?

**Comment by MichaelHiller** [comment]
What we call U12, includes U12 and non-canonical U2 introns (some of which are annotation artifacts present in GenCode or Refseq). 
With TOGA2 (coming soon), we used intronIC to classify introns and have 4 donor and 4 acceptor profiles for canonical and non-canonical U2 and U12 splice sites. They increase the accuracy of annotating exon boundaries.

**Comment by Alisa-1-lgtm** [comment]
Thank you for your quick reply.
I'm still confused. I have tried to use intronIC to classify introns in the human genome, but i have not been able to get such a number of U12 introns, only about 600.  As i said earlier, the number of U12 introns in the human example given by TOGA is more than 2000.At the same time, i want to know how to distinguish between the donor and acceptor?

**Comment by MichaelHiller** [comment]
As I said, we also list non-cano U2 in this file. AND our file comes from U12 DB, which is outdated and has errors.
