### ISSUE TITLE
What Criteria Should I Use to Work with Only One Chromosome or the Complete Genome?

### ISSUE THREAD

**Issue by MauriAndresMU1313** [hillerlab/TOGA#192]
Hi again, my goal is to use well-annotated species to improve the genome annotation of the ferret genome.

I'm using humans, mice, and dogs as references. My issue is that those reference genomes have multiple chromosomes available, in contrast, the ferret has only one chromosome.
If I follow your examples, you use one chromosome as a guide instead of the complete genome. What are the criteria for choosing this approach instead of using the complete genome?

I suppose that because my target genome has only one chromosome available, it is better to use one chromosome as a reference for my other species. However, I would like to understand the criteria behind that decision, and what chromosome is better for my analysis.
Any information is greatly appreciated!

**Comment by MichaelHiller** [comment]
What do you mean with "My issue is that those reference genomes have multiple chromosomes available, in contrast, the ferret has only one chromosome."

There is no mammal with a genome consisting of 1 chrom. You likely mean 'assemblies' instead of 'chromosomes'?

**Comment by MauriAndresMU1313** [comment]
My bad, I expressed it incorrectly. But yes, the ferret genome is assembled compared with the information available for the reference genomes that I want to use (dog, human, mice), which are in a better annotation stage. 
What criteria should I use to select one chromosome of the reference genomes to transfer that information to the ferret genome?

**Comment by MichaelHiller** [comment]
Since we already have TOGA with human (hg38) and mouse mm10 as the reference, you may only want to run it with dog as the reference and ferret as query. 

There are many dog genomes. The best genome in terms of gene completeness (TOGA stats) is canFam4. 
I would use this one and the NCBI refSeq annotation
https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_011100685.1/

**Comment by RMSlab** [comment]
Thank you for that suggestion, I will change to that version, I was not using that one. However, I still have the doubt about which chromosome to use. Let me give you an example: if I go to the input_test directory in the TOGA repository, your team selects chromosome 11. My question is, why that one and not another one?
