### ISSUE TITLE
How to use TOGA for inferring orthologous genes across multiple species?

### ISSUE THREAD

**Issue by swagttt1** [hillerlab/TOGA#193]
Sorry to bother, but I have a question that might be quite basic. @MichaelHiller 

I read a paper where the authors claim to have used TOGA to infer orthologous genes across 427 mammal species based on a MAF file of whole-genome alignments for 427 mammals (https://doi.org/10.1126/science.abn3263).

I'm not sure how they accomplished this, as the TOGA documentation seems to only include the process for inferring orthologs between two species (one as reference and another as query). 

Does anyone know how to use TOGA for inferring orthologous genes across multiple species?

**Comment by MichaelHiller** [comment]
They didn't use the multi genome ali to infer orthologous genes. Rather the same species included in the 427 mammal MAF also had TOGA data. 

TOGA only works with chains
