### ISSUE TITLE
Problem of merge_chains_output.py step

### ISSUE THREAD

**Issue by xjjago** [hillerlab/TOGA#2]
Hi:
When I used TOGA to test my data, I encountered "a list index out of range" error in the merge_chains_output.py step.The problem was solved by changing line 198 of the script from 
line_data = line.rstrip().split("\t") 
to
line_data = line[:-1].split("\t"). 

Best wishes.

**Comment by kirilenkobm** [comment]
Hi,

thank you for noticing that.
Indeed, I've automatically replaced this [:-1] with .rstrip() in the last commit. I will revert this change.
However, my tests didn't catch any issue here, so I am quite surprised.

I would be grateful if you could send me a file that caused this error.

Thank you.

**Comment by kirilenkobm** [comment]
Hi again,

I figured out what's wrong, so I'm closing the issue.
