### ISSUE TITLE
If isoform data not provied, how does it affect the results?

### ISSUE THREAD

**Issue by Abhishek7Nayak** [hillerlab/TOGA#21]
If isoform data is not provided TOGA treats each transcript as a gene and classifies lost, intact, etc.
If isoform data is given how does TOGA decide whether a particular gene is lost, intact, etc, because there can be multiple transcripts for a particular gene and some of the transcripts can be intact, lost, etc?

Thank you

**Comment by yuzhenpeng** [comment]
> If isoform data is not provided TOGA treats each transcript as a gene and classifies lost, intact, etc.
> If isoform data is given how does TOGA decide whether a particular gene is lost, intact, etc, because there can be multiple transcripts for a particular gene and some of the transcripts can be intact, lost, etc?
> 
> Thank you

I also have the same question with @Abhishek7Nayak .

**Comment by kirilenkobm** [comment]
Hi @yuzhenpeng and @Abhishek7Nayak,

If isoforms data is not provided, TOGA treats each transcript as an individual gene. So, each "gene" is represented by a single transcript.

If isoforms data is provided, gene class is defined as the "best" class of the underlying isoforms. For example, if isoform 1 or some gene X is classified as "Lost" and the second one is "Intact," the gene X is classified as "Intact."
