### ISSUE TITLE
CESAR jobs out of memory 

### ISSUE THREAD

**Issue by ramoseks** [hillerlab/TOGA#22]
Hi. I'm having problems with the memory usage required by CESAR jobs. It seems that my analysis has many long genes that are being rejected by TOGA. I tried using the --cb option setting to something like 8,16,32,64,128,256,512,1000, but when CESAR gets to the genes that need 128 or more memory it stops and gives me an "out of memory error message". In the log file I can see that I don't have jobs that need more than 256G, but it's not possible to run those that need memory between 64 and 256. I'm working on a system with 160 cpus and 1.47T of memory. I tried to further subdivide the jobs within this range of 64 - 256 setting more numbers as 8,16,32,64, 80,128, 150, 256 , but TOGA seems to ignore the numbers that I add in the --cb parameter in the log file (attached). There is another way to deal with this issue?
[toga_13_07.log](https://github.com/hillerlab/TOGA/files/6815439/toga_13_07.log)

**Comment by kirilenkobm** [comment]
Hi @ramoseks,

Thank you for the report.
I've analyzed the log file, and errors like this:
```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000800400000, 131072, 0) failed; error='Not enough space' (errno=12)
```
suggests that Nextflow (framework included in TOGA that manages parallel processes) tries to consume more memory than the server can provide. Typically, it should not happen. It seems like the communication between the system and nextflow is corrupted somehow (however, the first parallel step works completely fine). So, TOGA does not ignore the --cb parameter, the problem sits on another level.

As am idea, you can try to minimize the memory impact. Could you pls try the following parameters:
1) --cb 10,100,1000 --cjn 50
or
2) --cb 80,1000 --cjn 10?

Also, I will add a parameter to execute CESAR jobs paritions sequentially, not in parallel. I will inform you when it's done.

BR,
Bogdan

**Comment by kirilenkobm** [comment]
I've added --ces option, please also try this, for example:
--cjn 100 --cb 8,16,32,64,128,256,512,999 --ces 

In this case, TOGA will execute different partitions sequentially.
