### ISSUE TITLE
orthology_classification.tsv result is different with Blast [gene duplication error]

### ISSUE THREAD

**Issue by yuzhenpeng** [hillerlab/TOGA#23]
hello, I had one problem.

I compared the human genome and bowhead whale genome using lastz, then inferre the gene duplication and loss using TOGA.
I found one gene is marked one-to-one (one copy) in the orthology_classification.tsv of TOGA output. 
However, when I used Blast to check it. I found this gene have two copy.
Why the result is very different.

Could help me.

Thanks.

**Comment by kirilenkobm** [comment]
Hi,

Here, one-to-one means "TOGA detected a single orthologous copy," the second one (detected by BLAST) can easily be a paralog. Or processed pseudogene.

**Comment by yuzhenpeng** [comment]
> Hi,
> 
> Here, one-to-one means "TOGA detected a single orthologous copy," the second one (detected by BLAST) can easily be a paralog. Or processed pseudogene.

Hello, what does mean one-to-many and many-to-many in TOGA. Orthologs or paralogs?
