### ISSUE TITLE
CESAR big-mem

### ISSUE THREAD

**Issue by dianamosa** [hillerlab/TOGA#25]
Hello,

I am trying to run TOGA in mammalian genomes ~2gb, using human as a reference. 
I am working in a SLURM environment, and I know TOGA installation was successful because the wide-scale test ran properly. 

However, with my genomes it seems that the big-mem jobs are not getting done. According to the log file I am currently on STEP 7. I don't see any error message, but  I am getting a loop of messages like these:  

```
Iter 0 waiting 0 seconds Not done
Iter 1 waiting 60 seconds Not done
Iter 2 waiting 120 seconds Not done
Iter 3 waiting 180 seconds Not done
Iter 4 waiting 240 seconds Not done
Iter 5 waiting 300 seconds Not done
Iter 6 waiting 360 seconds Not done
Iter 7 waiting 420 seconds Not done
...
Iter 16720 waiting 1003200 seconds Not done
Iter 16721 waiting 1003260 seconds Not done

```

My code is:

```
./toga.py ${CHAIN} supply/hg38.v35.for_toga.bed hg38.2bit ${QUERY} \
        --kt --pd ${SPECIES} --nc ${NEXT}  --cb 10,100 --cjn 500 -i hg38.v35.for_toga.isoforms.tsv \
         --u12 hg38.U12sites.tsv --ms
```

My nextflow config files are:

```
// SLURM config file for CESAR jobs (not bigmem)
// since CESAR have various memory requirements, this
// is just a template, TOGA will fill this itself
// depending on the CESAR job bucket
process.executor = 'slurm'
process.queue = 'long-24core'
process.time = '24h'  // mostly 8h is enough, just for robustness
process.memory = "${_MEMORY_}G"  // to be replaced
process.cpus = 1  // CESAR utilizes a single core only
executor.queueSize = 1000  // nextflow default is 100 - too few
```

```
// SLURM config for bigmem CESAR jobs
// these jobs require huge amounts of memory and
// take too long
process.executor = 'slurm'
process.queue = 'extended-40'
process.memory = '100G'
process.time = '24h'
process.cpus = 40
```
I set up memory to 100G because I only have 160GB.
 
In my output dir I have the cesar_results files but only of the regular cesar jobs, not the big-mem. So my questions are:

1) Does the "Iter n waiting n seconds Not done" is a real error message? or is it showing an incorrect setup that will make my job to run really slow? If this is the case, could you help me to understand what am I missing?

2) Is there an option to kill toga at this step and restart from STEP 7 without submitting again the regular cesar jobs?

Thank you for your help with this!

**Comment by dengyuan7** [comment]
Hi,

Have you found any option to restart the program from STEP7 or other steps?

**Comment by 002-two** [comment]
Hi, I want to know how to get U12 introns data?  Thanks

**Comment by kirilenkobm** [comment]
Regarding the original questions that are likely not relevant anymore:
1 - it is just a regular cluster jobs logging - it was reconsidered in the recent releases for more clarity
2 - for now not, but step management is planned for TOGA 1.2.x (likely)
