### ISSUE TITLE
how to produce chain alignment file

### ISSUE THREAD

**Issue by code-acc** [hillerlab/TOGA#26]
Hi there!

I am new to making the genome alignment in chain format. Can you please guide on how to use GenomeAlignmentTools to make a chain file? I want to align two genomes of the same species. 

Thank you,
Minal

**Comment by MichaelHiller** [comment]
Hi Minal, 

our tools expect a chain file as input. 
The easiest way is to use doBlastzChainNet.pl pipeline which is part of the UCSC kent src code. 

- Michael

**Comment by kirilenkobm** [comment]
Pls try this pipeline:
https://github.com/hillerlab/make_lastz_chains

It supposes to be more portable.
