### ISSUE TITLE
No "proc_pseudogenes.bed" in the output

### ISSUE THREAD

**Issue by xin0107** [hillerlab/TOGA#27]
There is no "proc_pseudogenes.bed" in the TOGA output files.
At first, I found a “#” in front of the 752 line of code in toga.py, I thought I found the reason. However, after deleting "#" and re-submitting the task, there is still no  "proc_pseudogenes.bed" output. I checked the function and there seems to be no problem. I don't know what's going on right now.
![bb30fcce7a02b04f39998aac3322b0a](https://user-images.githubusercontent.com/89181971/146971479-23a3f65a-b4cb-459f-a371-aa8328ccfbbb.png)

In addition, the content in the log file is as following, it seems that the function is not working. I don't know where the problem is, because there is no error message.
<img width="986" alt="4bb2dfbf9045a41c0227579b2d62f0a" src="https://user-images.githubusercontent.com/89181971/146971315-826f95ef-10ba-4065-b9c0-18ea53d11be0.png">

Here is the shell script I used to run TOGA:
`python3 /opt/service/TOGA/toga.py Zk2mm39.chain mm39.nopseudo.bed mm39.genome.2bit zk.genome.v2.1.2bit --kt --pd $work_dir/project_dir2 --pn Zk --nd $work_dir/nextflow_temp2 --nc $work_dir/nextflow_config_files --cb 30,200,350 --cjn 70 -i mm39.isoform.txt --u12 mm10.U12sites.tsv --ms
`

And the output files:
<img width="566" alt="ced0689259ee242d3a4ce22d704fd6d" src="https://user-images.githubusercontent.com/89181971/147212771-4eb23205-ddf4-46fd-8e65-060c619c6fb6.png">

**Comment by xin0107** [comment]
Another ERROR：
When I run “./supply/plot_mutations.py”，I got an error:
```
[zx_test@gatk1 Visualization]$ python3 /opt/service/TOGA/supply/plot_mutations.py mm39.nopseudo.bed inact_mut_data.hdf5 ENSMUSG00000031142 Cacna1f.v1.svg -i isoform
Traceback (most recent call last):
  File "/opt/service/TOGA/supply/plot_mutations.py", line 1270, in <module>
    args.alt_template,
  File "/opt/service/TOGA/supply/plot_mutations.py", line 1218, in make_plot
    t_picture_width = comp_width(trans_data)
  File "/opt/service/TOGA/supply/plot_mutations.py", line 754, in comp_width
    + max(UTR_WIDTH, 2 * SS_LABEL_FONTSIZE)
IndexError: list index out of range
```
Can you solve this problem? Thanks a lot.

**Comment by yuzhenpeng** [comment]
I have the same problems.

**Comment by xin0107** [comment]
> 

I think TOGA may don't support that function.

**Comment by kirilenkobm** [comment]
Hi!

Adding this feature is planned in future releases.

- Bogdan

**Comment by kirilenkobm** [comment]
The recent TOGA version produces processed pseudogenes track
