### ISSUE TITLE
CESAR jobs crashed twice

### ISSUE THREAD

**Issue by dengyuan7** [hillerlab/TOGA#29]
Hi there,

I'm having issues with the bigmem jobs. The running program was aborted with the message that "Some CESAR jobs crashed twice" (log file attached). This should be caused by insufficient memory. I tried setting the --cb option to 20,500, but it still breaks off and reports the same error info. The solution should be to set a higher memory, but I'm wondering if I can just rerun the part of genes that requires a big memory.  It seems that most of the jobs have been done (inactivating mutations data can be found in the temp directory). Is there a way to extract the results of the finished jobs? 
[toga.orr.log](https://github.com/hillerlab/TOGA/files/8569195/toga.orr.log)

Thanks,
Yuan

**Comment by kirilenkobm** [comment]
Hi Yuan,

Unfortunately, there is currently no automated way to rerun only a portion of the CESAR jobs. However, we are planning to improve the management of CESAR jobs in the future, as we recognize that this is a feature in high demand.

We understand that CESAR memory requirements have been a challenge for many users, including ourselves. We are actively considering the development of a more memory-efficient version to address these issues.

Thank you for your patience and understanding.

Best regards,
