### ISSUE TITLE
Is it possible to run CESAR2.0 through TOGA only?

### ISSUE THREAD

**Issue by alejandrogzi** [hillerlab/TOGA#35]
Hi, 

I am having some trouble running CESAR2.0 due to libraries incompatibilities (long list of wrong library versions, etc...). Reading through CESAR2.0 issues I ended up here looking if I can run CESAR2.0 through TOGA alone. Since TOGA runs through netxflow and can be run through a docker container, all dependencies are precise, which would probably solve the issue.

Thanks in advance,
Alejandro

**Comment by kirilenkobm** [comment]
Hi, 

and sorry for the delayed response.
Unfortunately, TOGA is not packed into a docker container (some massive rearrangements in the pipeline are required to make it practical), so it just clones and builds CESAR2.0.
Did you already try using a precompiled binary? https://github.com/hillerlab/CESAR2.0/tree/master/precompiledBinary_x86_64

(btw, I can try to pack CESAR2.0 into docker, must be much easier that packing TOGA)

Best,
Bogdan
