### ISSUE TITLE
Toga install test 

### ISSUE THREAD

**Issue by jayramr** [hillerlab/TOGA#36]
Hi, 

i followed below steps on my sandbox to install toga 

```
conda  create -n  toga
conda activate toga
python3 -m pip install -r requirements.txt --user
conda install -c bioconda nextflow
./toga.py --help
```

Please update if cesar is needed as a prerequisite to run or can i proceed with this 

Thanks
Jay

**Comment by kirilenkobm** [comment]
Hi,

yes, CESAR is required. It is already linked as a git submodule.
Pls just call ./configure.sh script to compile it.
In addition, this script with train grad boost models that are also required.

Best,
Bogdan

**Comment by jayramr** [comment]
Sure let me test this and update you if any errors.

**Comment by jayramr** [comment]
I tested with the manual installation of toga , worked without any issues. 

Now I see that you toga.py script refers to the ```modules``` folder in the working directory. The way I'm writing the recipe for toga in bioconda fails to specify this modules path. 

Is it possible can you build this ```modules``` as a python package in pypi.org ? Please let me know if this is doable, so I can  smoothly finish completing the recipe.

Below is the PR for building the toga package.
https://github.com/bioconda/bioconda-recipes/pull/39056 

Thanks
Jay

**Comment by jayramr** [comment]
Hello @kirilenkobm please update

**Comment by kirilenkobm** [comment]
Apologies, but at the moment, I do not see a compelling reason to include the modules directory in a PyPi package. As it stands, this set of modules is tailored explicitly for TOGA and may not be applicable to other projects.
