### ISSUE TITLE
How to generate multiple codon alignment of target genes and select a mutations visualization of transcript to represent a gene

### ISSUE THREAD

**Issue by lnyawen** [hillerlab/TOGA#37]
Dear @MichaelHiller @kirilenkobm :

I got some questiones in generateing multiple codon alignment and visualization mutations. 

Firstly, I want to generate multiple codon alignment for some genes. I found a python script [extract_codon_alignment.py](https://github.com/hillerlab/TOGA/blob/master/supply/extract_codon_alignment.py) in supply. but there's a bug.
`FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/home/liunyw/howler_monkey/13.gene_loss/cleandir/HLcalJac4/t2bit.link'` . However, I didn't find t2bit.link, and it look like a process file which is created by TOGA. 

Therefor I run TOGA in real data. I performed TOGA based on the chain file obtained by [make_lastz_chains](https://github.com/hillerlab/make_lastz_chains). But I think there's something wrong. I use the command `grep 'GENE' loss_summ_data.tsv | wc -l ` in the TOGA result directory and get number 17,900, which means I annotated this species and got 17900 genes, is that right? And for the data downloaded from https://genome.senckenberg.de/download/TOGA/human_hg38_reference/Primates/, I used the same command `grep 'GENE' loss_summ_data.tsv | wc -l ` and got about 20,000.  I'm not sure if the 'Iter 1 waiting 60 seconds Not done' issue will have an impact on the results. 
```
#### STEP 7: Execute CESAR jobs: parallel step (the most time consuming)

Pushing 2 joblists
Pushed cluster jobs with nextflow /gpfs/home/liunyw/biosoft/TOGA/execute_joblist.nf --joblist /gpfs/home/liunyw/howler_monkey/06.alignment_lastz/TOGA/TOGA_cebAlb/temp/cesar_joblist_queue_3.txt -c /gpfs/home/liunyw/howler_monkey/06.alignment_lastz/TOGA/TOGA_cebAlb/temp/cesar_config_3_queue.nf
N E X T F L O W  ~  version 21.10.6
Launching `/gpfs/home/liunyw/biosoft/TOGA/execute_joblist.nf` [reverent_snyder] - revision: ae26d6b4bb
[-        ] process > execute_jobs -
executor >  pbs (2)
[f2/7c06e3] process > execute_jobs (7) [  0%] 0 of 284
executor >  pbs (9)
[00/ccc77b] process > execute_jobs (16) [  0%] 0 of 426
....................................................................................
....................................................................................
executor >  pbs (100)
[bb/b871de] process > execute_jobs (100) [  0%] 0 of 426
Iter 0 waiting 0 seconds Not done
executor >  pbs (81)
[4b/72ef98] process > execute_jobs (81) [  0%] 0 of 81
executor >  pbs (100)
[bb/b871de] process > execute_jobs (100) [  0%] 0 of 426
executor >  pbs (100)
[bb/b871de] process > execute_jobs (100) [  0%] 0 of 426
executor >  pbs (81)
[4b/72ef98] process > execute_jobs (81) [  0%] 0 of 81
Iter 1 waiting 60 seconds Not done
Iter 2 waiting 120 seconds Not done
Iter 3 waiting 180 seconds Not done
Iter 4 waiting 240 seconds Not done
Iter 5 waiting 300 seconds Not done
Iter 6 waiting 360 seconds Not done
Iter 7 waiting 420 seconds Not done
Iter 8 waiting 480 seconds Not done
....................................................................................
....................................................................................
```

Secondly, I want to visualizate for a gene, which is classified as a gene loss and containes some transcriptions. And I don't know which transcription can represent the gene. 
![image](https://user-images.githubusercontent.com/41319883/206656984-3656ed2e-6aaf-414a-80b5-744a9dbea5be.png)

Could you help me
Thank you.

Yawen

**Comment by MichaelHiller** [comment]
Hi, 
few comments and @kirilenkobm can fill in more details. 

The extract_codon_ali script likely requires the genome (2bit file). Bogdan can have a look if there is a parameter to point to the 2bit file. 

It looks like you are using assemblies for which we already ran TOGA and for which we already produced multiple codon alignments. Pls have a look if you can use these (and remove hundreds of other species that you don't care about): 
https://genome.senckenberg.de/download/TOGA/human_hg38_reference/MultipleCodonAlignments/

The visualization script makes one plot for every input transcript and each orthologous locus. You seem to have only a single transcript (ENST****0083) but apparently many chains that are classified as orthologous. Some chains likely span the gene and don't align it at all (those that have all grey exons). What is funky is that the other chains only align some but not all exons. 
Is this a really fragmented assembly, which would explain why there are so many chains that each align only a fragment? 

Best
Michael

**Comment by lnyawen** [comment]
Hello,

I found some gene I was interested in that didn't exist, like AMY1A, in this page https://genome.senckenberg.de/download/TOGA/human_hg38_reference/MultipleCodonAlignments/ . 

Does the visualization of ENST00000370083.AMY1A not show that this is a real gene loss?

Thanks.
Yawen

**Comment by lnyawen** [comment]
hello,

I have solved the error reported for generating multiple codon alignment. When I add the parameter --reference_2bit, the script [extract_codon_alignment.py](https://github.com/hillerlab/TOGA/blob/master/supply/extract_codon_alignment.py) runs successfully and generates the maf file.

Yawen

**Comment by MichaelHiller** [comment]
Hi, 
our [REAMDE](https://genome.senckenberg.de/download/TOGA/README.multipleCodonAlignments.txt) describes for which  genes we generated multiple codon alignments. 
If you can't find a multi codon ali for AMY1A, then this
"3) Two steps assure that alignments mostly (but not exclusively) include 1:1 orthologs. First, if a query assemblies has more than four predicted orthologs, we omitted this query assembly. Second, if the gene does not have a single (1:1) ortholog for at least 75% of all query species, we did not compute a multiple codon alignment for this gene. "
could be a possible reason. 

Wrt "visualization of ENST00000370083.AMY1A and gene loss" If you refer to the picture above, I would be careful with any conclusions, unless you are sure that the assembly is correct. Since the above picture indicates that there are several loci, each having potential assembly gaps, there is a chance that one or several of these loci actually contain an intact gene.

**Comment by lnyawen** [comment]
Hi

So I should double check the assembly of candidate genes contain gene AMY1A by mapping HiFi reads to genome (We dont have Illumina reads) firstly. And I check the ENST00000370083.AMY1A' coordinates,  found all transcripts locate on one contig.
```
$ grep AMY1A geneAnnotation.bed
ptg000007l      10672913        10673791        ENST00000370083.AMY1A.30372     1000    +       10672913        10673791        255,50,50       2       198,231,        0,647,
ptg000007l      10677699        10679877        ENST00000370083.AMY1A.103350    1000    +       10677699        10679877        130,130,130     3       119,126,190,    0,230,1988,
ptg000007l      10674465        10675730        ENST00000370083.AMY1A.118423    1000    +       10674465        10675730        130,130,130     3       134,123,100,    0,948,1165,
ptg000007l      10686898        10688767        ENST00000370083.AMY1A.120168    1000    -       10686898        10688767        130,130,130     3       187,127,119,    0,1512,1750,
ptg000007l      10701800        10702669        ENST00000370083.AMY1A.155283    1000    +       10701800        10702669        130,130,130     2       198,231,        0,638,
ptg000007l      10703368        10704670        ENST00000370083.AMY1A.209101    1000    +       10703368        10704670        130,130,130     3       134,123,100,    0,985,1202,
ptg000007l      10708314        10708504        ENST00000370083.AMY1A.223021    1000    +       10708314        10708504        130,130,130     1       190,    0,
ptg000007l      10690718        10691035        ENST00000370083.AMY1A.356067    1000    -       10690718        10691035        130,130,130     2       100,123,        0,194,
ptg000007l      10691843        10691977        ENST00000370083.AMY1A.446212    1000    -       10691843        10691977        130,130,130     1       134,    0,
ptg000007l      10706634        10706990        ENST00000370083.AMY1A.506259    1000    +       10706634        10706990        130,130,130     2       119,126,        0,230,
ptg000007l      10700460        10700607        ENST00000370083.AMY1A.823400    1000    +       10700460        10700607        130,130,130     1       147,    0,
```
And the coordinates of AMY1C/AMY2A/AMY2B(intact gene) include AMY1A' coordinates.  So the AMY1A gene loss is most likely not a real gene loss, right?

**Comment by MichaelHiller** [comment]
The bed file lists all locations where TOGA detected orthologous fragments. 

Can you post a genome browser screenshot of how the chains look like? 
And what is the phylogenetically closest species for which we have run TOGA?

**Comment by lnyawen** [comment]
hello

I don't have the chain file of the genome alignment, because when I was about to download the alignment file, I found that the link you provided was invalid. It was my fault that I didn't download it in time.

And I check _Alouatta Caraya'_ phylogenetically closest species -- _Alouatta palliata_(https://genome.senckenberg.de/download/TOGA/human_hg38_reference/Primates/Alouatta_palliata__mantled_howler_monkey__HLaloPal1/loss_summ_data.tsv.gz). I found the gene AMY1A(ENSG00000237763) was also classified as a gene loss. Does this prove that the gene is indeed lost?

**Comment by MichaelHiller** [comment]
Lets take this offline as this is not a TOGA-related issue anymore. I'll email you.

**Comment by lnyawen** [comment]
OK, Thank you! I'll close this issue.
