### ISSUE TITLE
Questions about transcripts with chain ID "-1" and transcript/gene classifications

### ISSUE THREAD

**Issue by sz-1002** [hillerlab/TOGA#39]
Hi,

First of all, thank you for helping me install CESAR [https://github.com/hillerlab/CESAR2.0/issues/16](url). Really appreciated it, and very nice tool indeed.

Recently, I have been trying TOGA and I have a question about the TOGA results. In e.g. the mammals results from [https://genome.senckenberg.de/download/TOGA/human_hg38_reference/](url), sometimes there seems to be transcripts with chain ID "-1" that has only part of the transcript in the geneAnnotation file but the complete sequence in the codonAlignment file (and the gene is classified as "intact"). 

For instance, in HLzapHud1,

```
PVHP010000627   2125    17164   ENST00000644269.SLC26A4.-1      1000    +       2125    17164   0,0,200 8       70,93,96,231,55,146,84,24,     0,2007,4471,5397,7950,9941,12935,15015,

PVHP010051346   5793    7557    ENST00000037243.GABARAPL2.-1    1000    -       5793    7557    0,0,200 3       173,56,34,      0,1456,1730,
```

I am guessing that these represent fragmented sequences where multiple scaffolds are joined together to get the complete sequence, but for some reason some scaffolds are dropped from the geneAnnotation file (and, HLzapHud1 seems to be a rather fragmented assembly). Is this right? If so,  are there any ways to recover all the scaffolds that contributed to the sequence?

I have another question about the transcript/gene classifications. In general, which classes should be considered as good enough evidence of the gene being present in the genome? (Intact, Partially intact & Uncertain loss?) (e.g., I was wondering which ones should be used when calculating BUSCO scores).

Thank you very much!!

**Comment by kirilenkobm** [comment]
Hi @sz-1002 ,

and sorry for the delayed response.
Normally, to name an annotated transcript in the query genome, TOGA uses the parent transcript ID from the reference genome and the identifier of the orthologous chain that was used to annotate this precise transcript.
So they are named as ${transcriptID in the reference}.${orthologous chain ID}

This system was quite beneficial - identifiers of annotated transcripts already carried the necessary information about its source. However, it didn't work well with fragmented sequences (long story). So yes, -1 marks fragmented annotations.

For example, a scaffold might be dropped if the orthologous fragment aligns only to introns, or all of the exons expected to be found were classified as deleted/missing on this fragment. The latest TOGA version should create a file called temp/gene_fragments.txt in the output directory. Here, for each reference transcript fragmented in the query, it lists IDs of orthologous chains that are expected to contribute to the sequence. (pls let me know if the file is absent)

Then, from chainIDs, you may infer respective scaffold IDs.

About the second question.
Intact - is definitely a piece of good evidence.
Partially Intact is rather 50:50. The gene is not fully present in the given assembly, but maybe is actually present in the genome. The missing parts may contain an intact sequence.
Uncertain loss - quite risky. For such genes, there is not enough evidence to say they are likely lost. All the found inactivating mutations could be assembly artifacts or could be real. It is hard to say, additional research is needed (for example, manually inspecting the raw reads - is this mutation still present there or not?)

**Comment by sz-1002** [comment]
@kirilenkobm 

Thank you very much for your very detailed answer!

So, about sequences with chain ID "-1", if they are classified as "Intact", then they can still be considered a normal full-length (or close to full-length) sequence, even though some contributing scaffolds may have been dropped, right? Or is it still case-by-case?

**Comment by kirilenkobm** [comment]
@sz-1002 

exactly!
For transcripts to be classified as "intact," they must retain at least 80% of the original reading frame.
