### ISSUE TITLE
Problems with Compiling C Code at ./configure.sh step

### ISSUE THREAD

**Issue by saxovocal** [hillerlab/TOGA#4]
After cloning the git repository, and making sure I have a conda environment that contains nextflow and all the packages required in the 'requirements.txt' file, I run ./configure.sh as instructed. I have the following error

```
Compiling C code...
In file included from ./modules/chain_coords_converter_slib.c:22:
./modules/chain.h: In function 'parse_head':
./modules/chain.h:43: warning: missing initializer
./modules/chain.h:43: warning: (near initialization for 'head.tName')
./modules/chain.h: In function 'parse_block':
./modules/chain.h:95: warning: missing initializer
./modules/chain.h:95: warning: (near initialization for 'block.size')
In file included from ./modules/extract_subchain_slib.c:32:
./modules/chain.h: In function 'parse_head':
./modules/chain.h:43: warning: missing initializer
./modules/chain.h:43: warning: (near initialization for 'head.tName')
./modules/chain.h: In function 'parse_block':
./modules/chain.h:95: warning: missing initializer
./modules/chain.h:95: warning: (near initialization for 'block.size')
./modules/chain_bst_lib.c:34: warning: missing initializer
./modules/chain_bst_lib.c:34: warning: (near initialization for 'NOTHING.chain_id')
./modules/chain_bst_lib.c: In function 'print_point':
./modules/chain_bst_lib.c:55: warning: format '%llu' expects type 'long long unsigned int', but argument 2 has type 'uint64_t'
./modules/chain_bst_lib.c:56: warning: format '%llu' expects type 'long long unsigned int', but argument 2 has type 'uint64_t'
./modules/chain_bst_lib.c:57: warning: format '%llu' expects type 'long long unsigned int', but argument 2 has type 'uint64_t'
```

Not quite sure how to proceed with this! Help would be really appreciated :)

**Comment by kirilenkobm** [comment]
Hi,

thank you for your message.
That's interesting, I tested this on various operating systems/gcc and never seen this.
What gcc version do you use?
There are just warnings, seems like your compiler is overly paranoid.
I guess everything is compiled and should work.

Anyway I'll make some changes to suppress the warnings.

**Comment by kirilenkobm** [comment]
Alright, I updated chain.h and chain_bst_lib.c, compliler should not complain
https://github.com/hillerlab/TOGA/commit/80082249c37d54af8fdc892cb3498f95723bed57

**Comment by saxovocal** [comment]
Thank you so much for replying.

Indeed, the compiler does go through when testing with ./run_test.sh micro.

However, I do note that (or I might be mistaken) that ./configure.sh does not download CESAR2.0 automatically. I manually downloaded it and hard linked it to the TOGA directory as the error was ./cesar not found.

After doing so, I ran ./run_test.sh micro. This goes all the way through until the end, with the follow errors:

```
CESAR jobs done
Pushed cluster jobs with nextflow /gpfs/pteropus/Data/TOGA/TOGA/execute_joblist.nf --joblist /gpfs/pteropus/Data/TOGA/TOGA/micro_test_out/cesar_combinedMerging CESAR output to make final fasta and pre-final bed files.
Warning! cesar_job_1_0.bdb is empty
Saving the output
! merge_cesar_output.py:
No projections found! Abort.
```

Is this a problem with nextflow?

**Comment by saxovocal** [comment]
Thank you so much. The precompiled binary works after I link it under CESAR2.0. Will this binary also be updated in the CESAR github? helps a lot!

**Comment by kirilenkobm** [comment]
Nice. 
Yep, it will be updated.
