### ISSUE TITLE
How could I use the loss_summ_data.tsv combined with  inact_mut_data.txt to draw the figure like the following one?

### ISSUE THREAD

**Issue by lirui-max** [hillerlab/TOGA#45]
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/53031079/216602436-b4c8d4cf-7b33-40e7-8829-2d6a334ae1b4.png">

**Comment by kirilenkobm** [comment]
Hi @lirui-max 

Pls use the script `./supply/plot_mutations.py`

```
usage: plot_mutations.py [-h] [--chain CHAIN] [--isoforms_file ISOFORMS_FILE] [--multi_species] [--alt_template ALT_TEMPLATE] [--publication_mode_heni] [--verbose]
                         bed_file toga_mut_file transcripts output

positional arguments:
  bed_file              Reference annotation, bed12 file
  toga_mut_file         TOGA mutations - path to  inact_mut_data.txt file
  transcripts           Transcripts of interest (comma-sep list or a single one)
  output                Path to output image

optional arguments:
  -h, --help            show this help message and exit
  --chain CHAIN         Limit to a particular projection (in case there are many orthologous projections, coming from chains 1,2 and 3, but user needs only those that come from 2)
  --isoforms_file ISOFORMS_FILE, -i ISOFORMS_FILE
                        If you provide geneID instead of transcript, please also provide an isoforms file.
  --multi_species, --ms
                        Please see documentation which is not yet written
  --alt_template ALT_TEMPLATE, -a ALT_TEMPLATE
                        Alternative template path
  --publication_mode_heni, --pmh
                        Publication mode; Indrischek et al. 2021 version
  --verbose, -v
```

**Comment by lirui-max** [comment]
Thank you very much, I will try it quickly.
In your recent paper, you chose ISG15 to validate the specific immune system in bats.&nbsp;
How could you select this ISG15 gene from the huge amount of genes in the results of positive selection?



发自我的iPhone


------------------ Original ------------------
From: Bogdan Kirilenko ***@***.***&gt;
Date: Sun,May 7,2023 6:20 PM
To: hillerlab/TOGA ***@***.***&gt;
Cc: lirui-max ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [hillerlab/TOGA] How could I use the loss_summ_data.tsv combinedwith  inact_mut_data.txt to draw the figure like the following one? (Issue#45)





 
Hi @lirui-max
 
Pls use the script ./supply/plot_mutations.py
 usage: plot_mutations.py [-h] [--chain CHAIN] [--isoforms_file ISOFORMS_FILE] [--multi_species] [--alt_template ALT_TEMPLATE] [--publication_mode_heni] [--verbose]                          bed_file toga_mut_file transcripts output positional arguments:   bed_file              Reference annotation, bed12 file   toga_mut_file         TOGA mutations - path to  inact_mut_data.txt file   transcripts           Transcripts of interest (comma-sep list or a single one)   output                Path to output image optional arguments:   -h, --help            show this help message and exit   --chain CHAIN         Limit to a particular projection (in case there are many orthologous projections, coming from chains 1,2 and 3, but user needs only those that come from 2)   --isoforms_file ISOFORMS_FILE, -i ISOFORMS_FILE                         If you provide geneID instead of transcript, please also provide an isoforms file.   --multi_species, --ms                         Please see documentation which is not yet written   --alt_template ALT_TEMPLATE, -a ALT_TEMPLATE                         Alternative template path   --publication_mode_heni, --pmh                         Publication mode; Indrischek et al. 2021 version   --verbose, -v

**Comment by MichaelHiller** [comment]
The ISG15 gene doesn't belong to the TOGA github, but briefly, it has a key Cys deletion, is highly-relevant for immunity and Covid19, etc. More in our preprint.
