### ISSUE TITLE
 CESAR jobs error: Iter 4381 waiting 262860 seconds Not done

### ISSUE THREAD

**Issue by mengting-Ding** [hillerlab/TOGA#51]
Hi,
I got some trouble when running TOGA step 7, meeting with the warning " Iter 4381 waiting 262860 seconds Not done"

The toga log file displays that TOGA needs to go through the following steps:
#### STEP 5: Generate CESAR jobs
# STEP 6: RESERVED (PLACEHOLDER)
#### STEP 11: Cleanup: merge parallel steps output files

After the task， I got the following files:
done.status, temp,inact_mut_data.txt, genes_rejection_reason.tsv, ref_orphan_transcripts.txt, orthology_classification.tsv, query_gene_spans.bed, query_isoforms.tsv, loss_summ_data.tsv, query_annotation.bed, query_annotation.bed, codon.fasta, prot.fasta, nucleotide.fasta, project_args.json, q2bit.link, t2bit.link

while I noticed that when TOGA reaches step 7 Execute CESAR jobs, the stdout file displays many tips like this: 
“
executor >  Local (501)
[a6/d3c375] process > execute_jobs (498) [ 98%] 495 of 501
Iter 4380 waiting 262800 seconds Not done
Iter 4381 waiting 262860 seconds Not done
executor >  Local (501)
[a5/70d903] process > execute_jobs (494) [ 99%] 496 of 501
......
"
I tried to add memory to run TOGA, but it didn't help.I cannot understand if this is normal or not. Do I need to make adjustments for it, and how do I resolve the error?

My scripts are as follows:
toga.py $chain $bed $reference $query_bit \
 --kt \
 --project_name result \
 -i $isoforms \
 --nc /nextflow_config_files \
 --nd ./nextflow_logs \
 --cjn 500 \
 --ms

Any ideas appreciated

Thanks
Mengting

**Comment by kirilenkobm** [comment]
Hi,

The message "Iter 4381 waiting 262860 seconds Not done" simply indicates the amount of time spent on CESAR jobs. It is not a cause for concern (unless an excessive amount of time is being spent on these jobs).
