### ISSUE TITLE
The number of genes annotated is low

### ISSUE THREAD

**Issue by lnyawen** [hillerlab/TOGA#52]
Dear @MichaelHiller @kirilenkobm 

When I ran a TOGA on the genomes of some primates, I discovered that the number of genes I annotated to was on the low side, about 18,000 genes. I downloaded the file for the primate from the website (https://genome.senckenberg.de/download/TOGA/human_hg38_reference/Primates/) and found annotations to over 19,000 genes.

I downloaded the human genome from the UCSC website (https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz) and using software make_lastz_chain to obtained human-primate alignment files(chain file). The genome was then annotated using TOGA. Use this command to calculate the number of genes annotated.
```
awk '{print $4}' query_annotation.bed |  awk -v FS="." '{print $2}' | sort -u| wc -l
17764
```
What may be causing this? Any assistance is much appreciated!

Yawen

**Comment by kirilenkobm** [comment]
Dear @lnyawen,

Could you please provide some additional information to help us better understand your situation:

- The total number of transcripts annotated in the query_annotation.bed file
- The statistics for genes found in the gene_loss_summary.tsv file (how many Lost, Missing, etc)
- The query genome assembly you are using
It is important to note that the quality of some primate genomes can be relatively low, which may impact the accuracy of TOGA results. Assembly artifacts could lead to incorrect classification of gene losses, or certain regions might not be present at all in the query assembly.

Please let us know the details mentioned above, and we will be better equipped to assist you.

**Comment by lnyawen** [comment]
Sorry to open this up again.
Once again, I'm running into a situation where the number of genes calculated is not equal to the number of genes in the REFERENCE. And I had to face this problem.

I calculated the results for 21 genomes and the number of genes annotated by TOGA is as follows (grep ‘GENE’ loss_summ_data.tsv | wc -l):
```
vs_allLho 19434
vs_aotVoc 19439
vs_atePan 19441
vs_calJac 19438
vs_gorGor 19430
vs_hooLeu 19435
vs_macAss 19435
vs_macAss 19439
vs_macLeo 19439
vs_macMul 19443
vs_macLeo 19439 vs_macMul 19443
vs_macAss 19439 vs_macLeo 19439
vs_papHam 19443
vs_papHam 19441
vs_PitPit 19438
vs_ponAbe 19419
vs_ponPyg 19393
vs_ponAbe 19419 vs_ponPyg 19393
vs_ponAbe 19419 vs_ponPyg 193939 vs_rhiBie 19371
vs_symSyn.ee 19440
vs_tupBel 19456
```
The number of annotated out genes should be 19464, consistent with the reference used.
And the classification of ancestral genes is as follows:
intact genes genes with inactivating mutations genes with missing sequence
```
vs_allLho 18084 296 50
vs_aotVoc 17749 605 76
vs_atePan 17896 465 69
vs_calJac 17800 563 67
vs_gorGor 18160 227 43
vs_hooLeu 17918 453 59
vs_macAss 17777 559 89
vs_macAss 17776 355 299
vs_macLeo 18082 300 48
vs_macMul 18090 286 54
vs_nycBen 17583 661 186
vs_panPan 18198 188 44
vs_panTro 16555 183 1692
vs_papHam 18096 294 40
vs_PitPit 17847 511 72
vs_ponAbe 18071 307 52
vs_ponPyg 18053 298 79
vs_rhiBie 17875 442 113
vs_symSyn 17902 474 54
vs_symSyn.ee 17908 468 54
vs_tupBel 17730 601 99
```

Need some more info?
Thank you for your help in advance!

Yawen

**Comment by lnyawen** [comment]
In addition the genome quality should be fine, it is a T2T genome assembled with high coverage.

**Comment by MichaelHiller** [comment]
Hi Yawen, 

I thought I answered this a few days ago, but my response was likely not saved. 

1) There are a few reasons when TOGA can't compute anything. Some genes are not covered by any chains (chains start/end outside the genes), which can happen in case of rearrangements. Sometimes the chain aligns a gene to a query locus that is very large and exceeds the memory limit (often a case of chain mis-alignment). TOGA1 drops these genes. The upcoming TOGA2 can handle these cases. 
This typically explains why the total number of annotated genes differs slightly. 


2) Something similar probably applies to the ancestral gene subset. 

TOGA produces a genes_rejection_reason.tsv file that has 'codewords' as "too long query locus", "number of chains (100 chains) limit exceeded", "all exons are deleted." and "no intersecting chains".

Pls have a look what this file says for the genes not found. 
If you send me a few ancestral genes that are missing in the loss_sum file for a species, I can also have a look.

Thx

**Comment by lnyawen** [comment]
Hello Prof Michael Hiller,

Thank you very much for your reply!

```
ENSG00000198947 19
ENSG00000188107 19
ENSG00000168702 19
ENSG00000131018 19
ENSG00000042781 19
ENSG00000140836 17
ENSG00000183117 15
ENSG00000155657 15
ENSG00000135976 14
ENSG00000180777 10
```

I did a count of the unannotated genes, and here's a little bit of the data, with the gene ID on the left and the number of unannotated species on the right. For those genes that are not annotated in most species, they don't even appear to appear in genes_rejection_reason.tsv.

Thanks
Yawen

**Comment by MichaelHiller** [comment]
Which query species?

**Comment by MichaelHiller** [comment]
Or are these missing not annotated in all species?

**Comment by lnyawen** [comment]
> Or are these missing not annotated in all species?

Yes, Basically this shoe gene is not annotated in all species.

**Comment by MichaelHiller** [comment]
I looked at the first ENSG00000198947 (DMD) and 4 representative primates. TOGA annotates them in 3 of them:
`g ENSG00000198947 vs_tupBel1/loss_summ_data.tsv vs_HLatePan1/loss_summ_data.tsv vs_HLrhiBie2/loss_summ_data.tsv vs_panTro6/loss_summ_data.tsv 
vs_tupBel1/loss_summ_data.tsv:GENE	ENSG00000198947	UL
vs_HLrhiBie2/loss_summ_data.tsv:GENE	ENSG00000198947	I
vs_panTro6/loss_summ_data.tsv:GENE	ENSG00000198947	I
`

for atePan, the gene is fragmented into a lot of chains, and while TOGA in principle should identify the orthologous pieces, I assume the gene is too fragmented. 
Indeed, the genes_rejection_reason.tsv has entries for the transcripts of this gene as
`g ENST00000619831 vs_HLatePan1/genes_rejection_reason.tsv 
/projects/hillerlab/genome/src/TOGA_pub/CESAR_wrapper.py ENST00000619831.DMD 4010,5292,10170,10900,11726,12655,15290,16627,18238,19806,20594,26640,18227 /projects/hillerlab/genome/gbdb-HL/hg38/TOGA/vs_HLatePan1/temp/toga_filt_ref_annot.hdf5 /projects/hillerlab/genome/gbdb-HL/hg38/TOGA/vs_HLatePan1/temp/genome_alignment.bst /projects/hillerlab/genome/gbdb-HL/hg38/hg38.2bit /projects/hillerlab/genome/gbdb-HL/HLatePan1/HLatePan1.2bit --cesar_binary /projects/hillerlab/genome/src/TOGA_pub/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --fragments --alt_frame_del --memlim 120	fragment chains oevrlap`

![image](https://github.com/user-attachments/assets/4bbdbf4d-b814-4c35-94c1-bd06a8afb217)

**Comment by MichaelHiller** [comment]
Similar for the next gene (EYS).
`g ENSG00000188107 vs_tupBel1/loss_summ_data.tsv vs_HLatePan1/loss_summ_data.tsv vs_HLrhiBie2/loss_summ_data.tsv vs_panTro6/loss_summ_data.tsv 
vs_tupBel1/loss_summ_data.tsv:GENE	ENSG00000188107	UL
vs_HLrhiBie2/loss_summ_data.tsv:GENE	ENSG00000188107	I
vs_panTro6/loss_summ_data.tsv:GENE	ENSG00000188107	UL
`

`g ENST00000370621 vs_HLatePan1/genes_rejection_reason.tsv 
/projects/hillerlab/genome/src/TOGA_pub/CESAR_wrapper.py ENST00000370621.EYS 9300,10188,13261,13366,19615,19952,20451,22109,25764 /projects/hillerlab/genome/gbdb-HL/hg38/TOGA/vs_HLatePan1/temp/toga_filt_ref_annot.hdf5 /projects/hillerlab/genome/gbdb-HL/hg38/TOGA/vs_HLatePan1/temp/genome_alignment.bst /projects/hillerlab/genome/gbdb-HL/hg38/hg38.2bit /projects/hillerlab/genome/gbdb-HL/HLatePan1/HLatePan1.2bit --cesar_binary /projects/hillerlab/genome/src/TOGA_pub/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --fragments --alt_frame_del --memlim 50	fragment chains oevrlap`

![image](https://github.com/user-attachments/assets/d10be419-8565-4254-9899-481717b24db5)

Though we need to check why this gene was not stitched together from the fragmented pieces. Maybe

**Comment by MichaelHiller** [comment]
Same for gene 3

`g ENSG00000168702 vs_tupBel1/loss_summ_data.tsv vs_HLatePan1/loss_summ_data.tsv vs_HLrhiBie2/loss_summ_data.tsv vs_panTro6/loss_summ_data.tsv toga.isoforms.tsv 
vs_tupBel1/loss_summ_data.tsv:GENE	ENSG00000168702	UL
vs_HLrhiBie2/loss_summ_data.tsv:GENE	ENSG00000168702	I
vs_panTro6/loss_summ_data.tsv:GENE	ENSG00000168702	I
toga.isoforms.tsv:ENSG00000168702	ENST00000389484.LRP1B


g ENST00000389484 vs_HLatePan1/genes_rejection_reason.tsv 
/projects/hillerlab/genome/src/TOGA_pub/CESAR_wrapper.py ENST00000389484.LRP1B 1531,1627,2593,2906,3673,6264,11807,13939,14146,14960,17238,18358,20876,21610,27385 /projects/hillerlab/genome/gbdb-HL/hg38/TOGA/vs_HLatePan1/temp/toga_filt_ref_annot.hdf5 /projects/hillerlab/genome/gbdb-HL/hg38/TOGA/vs_HLatePan1/temp/genome_alignment.bst /projects/hillerlab/genome/gbdb-HL/hg38/hg38.2bit /projects/hillerlab/genome/gbdb-HL/HLatePan1/HLatePan1.2bit --cesar_binary /projects/hillerlab/genome/src/TOGA_pub/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --fragments --alt_frame_del --memlim 250	fragment chains oevrlap`

![image](https://github.com/user-attachments/assets/fc93028e-798a-46a1-9cad-af7c8b288838)

**Comment by MichaelHiller** [comment]
So I think most of these genes are indeed present and annotated, except in a species that has a super fragmented genome (only contigs, and contig N50 is just 58589 bp and there are 98070 contigs in total).

But it is not the case that these genes are missing from the TOGA annotation for 19 primates.

**Comment by lnyawen** [comment]
Yes, I also looked at the annotation results for different assemblies of the same species in https://genome.senckenberg.de/download/TOGA/human_hg38_reference/Primates/ and those genes are annotated and present. It's just that they are not annotated in the results of my own run.

And what do you think I should do to fix this?

Thanks!

**Comment by MichaelHiller** [comment]
Did you generate the chains yourself? If so, I can send you mine for one species where we have the same assembly and then you can check whether you get the same results with TOGA.

**Comment by MichaelHiller** [comment]
OK, but one thought first. Many of the genes I looked at are long (DMD, EYS) and need a lot of memory. What is your memory limit that you specified? 
Could you make a test run where you only have say DMD and EYS in the input and you specifiy say 250 or 300 GB RAM limit (if you have that much)? 
Do you annotate TNT (titin) for the primates? 
This could be a likely reason why these genes are missing from your runs.

We will release TOGA2 soon, which requires only 10 GB for annotate pretty much everything.

**Comment by lnyawen** [comment]
Yes, I generated the alignment chain using make_lastz_chain with default parameters. Ok, then please send me a random species with better assembly quality I'll test it.

**Comment by lnyawen** [comment]
> OK, but one thought first. Many of the genes I looked at are long (DMD, EYS) and need a lot of memory. What is your memory limit that you specified? Could you make a test run where you only have say DMD and EYS in the input and you specifiy say 250 or 300 GB RAM limit (if you have that much)? Do you annotate TNT (titin) for the primates? This could be a likely reason why these genes are missing from your runs.
> 
> We will release TOGA2 soon, which requires only 10 GB for annotate pretty much everything.

Okay, I'll do the memory limit test. The average compute node on our side runs at about 260GB of memory.
However, the TNT genes are annotated for all species.
Looking forward to the release of TOGA2.

**Comment by lnyawen** [comment]
I took DMD and EYS out of toga.isoforms.tsv and replaced the original toga.isoforms.tsv.
However log prompts:

```
### STEP 7: Execute CESAR jobs: parallel step

Pushing 5 CESAR job lists
Pushing memory bucket 5Gb to the executor
There are no jobs in the 5Gb bucket
Pushing memory bucket 15Gb to the executor
There are no jobs in the 15Gb bucket
Pushing memory bucket 50Gb to the executor
There are no jobs in the 50Gb bucket
Pushing memory bucket 100Gb to the executor
There are no jobs in the 100Gb bucket
Pushing memory bucket 300Gb to the executor
Selected parallelization strategy: nextflow
Parallel manager: pushing job nextflow /lustre/home/luyizheng/liunyw/project/primate_geneloss/software/TOGA/execute_joblist.nf --joblist /lustre/home/luyizheng/liunyw/project/primate_geneloss/geneloss/test/TOGA_hg38_aotVoc/temp/cesar_joblist_queue_300.txt -c /lustre/home/luyizheng/liunyw/project/primate_geneloss/geneloss/test/TOGA_hg38_aotVoc/temp/cesar_config_300_queue.nf
## Stated polling cluster jobs until they done
### CESAR jobs done ###

Checking whether all CESAR results are complete
No CESAR jobs crashed according to rejection log
Logs from individual CESAR jobs are show below


#### STEP 8: Merge STEP 7 output

Merging CESAR output to make fasta and bed files.
merge_cesar_jobs: module called with arguments:
* input_dir: /lustre/home/luyizheng/liunyw/project/primate_geneloss/geneloss/test/TOGA_hg38_aotVoc/temp/cesar_results
* output_bed: /lustre/home/luyizheng/liunyw/project/primate_geneloss/geneloss/test/TOGA_hg38_aotVoc/temp/intermediate.bed
* output_fasta: /lustre/home/luyizheng/liunyw/project/primate_geneloss/geneloss/test/TOGA_hg38_aotVoc/nucleotide.fasta
* meta_data_arg: /lustre/home/luyizheng/liunyw/project/primate_geneloss/geneloss/test/TOGA_hg38_aotVoc/temp/exons_meta_data.tsv
* skipped_arg: /lustre/home/luyizheng/liunyw/project/primate_geneloss/geneloss/test/TOGA_hg38_aotVoc/temp/rejected/CESAR_MERGE.txt
* prot_arg: /lustre/home/luyizheng/liunyw/project/primate_geneloss/geneloss/test/TOGA_hg38_aotVoc/prot.fasta
* codon_arg: /lustre/home/luyizheng/liunyw/project/primate_geneloss/geneloss/test/TOGA_hg38_aotVoc/codon.fasta
* output_trash: /lustre/home/luyizheng/liunyw/project/primate_geneloss/geneloss/test/TOGA_hg38_aotVoc/temp/trash_exons.bed
* fragm_data: /lustre/home/luyizheng/liunyw/project/primate_geneloss/geneloss/test/TOGA_hg38_aotVoc/temp/bed_fragments_to_exons.tsv
* exclude: None
merge_cesar_jobs: merging CESAR results from 0 output files
merge_cesar_jobs: Saving the output
merge_cesar_jobs: CRITICAL: could not extract any bed lines from the CESAR output, abort
```

**Comment by MichaelHiller** [comment]
Sounds like they both go into the 300 GB bucket and that there is a problem with running them. 
You said your machines have ~250 GB of mem, right? I think 250 should be enough for both genes. Could you pls try to run it with --cesar_buckets 10,250? 
Maybe this helps.

**Comment by lnyawen** [comment]
It works! 

I just did a complete calculation of TOGA for one species and got the total number of annotated genes to be 19,464.
It's hard to imagine such a tiny parameter causing this issue. 

Thanks a lot!

**Comment by MichaelHiller** [comment]
Great to hear. 

Again, with TOGA 2 things will be become simper as it requires ~300X less memory and 10 GB is sufficient for pretty much everything

**Comment by lnyawen** [comment]
For mouse based annotation results, I found that most species are not annotated with 22257
 (awk ‘{print $1}’ TOGA/TOGAInput/mouse_mm10/toga.isoforms.tsv | grep -v GeneID | sort -u | wc -l).
The following is a list of all the forms that are available on your website. Even the number of annotation results downloaded from your website is less than 22257, can I ignore this problem for results base mm10?

**Comment by lnyawen** [comment]
> Great to hear.
> 
> Again, with TOGA 2 things will be become simper as it requires ~300X less memory and 10 GB is sufficient for pretty much everything

Very much looking forward to it!

**Comment by MichaelHiller** [comment]
Yes, if the number is close to 22k, I think it should be fine. As I explained above, some genes can't be annotated / classified in some genomes for biological or technical reasons

**Comment by lnyawen** [comment]
Okay! Thank you very much for your help!
