### ISSUE TITLE
term definition in file gene_rejaction_reasons.tsv

### ISSUE THREAD

**Issue by DiegoSafian** [hillerlab/TOGA#53]
Hi,

I just successfully run TOGA. The tools is great, thanks!
I just have one question about the gene_rejaction_reasons.tsv. Could you please define:

Out-of-frame gene, No classifiable chains, all exons are deleted, chromosome is not aligned and no intersecting chains ?

Thanks again,
Diego

**Comment by MichaelHiller** [comment]
Good point. 
I think out of frame gene refers to a gene annotation in the reference that is not in frame or has an internal (non TGA) stop.
No classifiable or intersecting chains and chrom not aligned likely refers to genes that have no spanning or no chain at all --> such genes should be classified as missing. 

@kirilenkobm Can you pls have a look and provide a definition on the main page?

**Comment by DiegoSafian** [comment]
Dear Michael,
Thanks for your reply. I will be waiting for reply.
I have a other question about lastZ. I aligned two genomes (700Mb) using Lastz, but the problem is that although my command has been running fine and I am getting an output file (--format=axt), the output file reaches 250 Mb and stops increasing despite the job having been running for 10 hrs. I wonder what is going on here and if I am doing something wrong. This si my command:

**Comment by MichaelHiller** [comment]
The size of the output file depends on the evolutionary distance. We typically split a genome into many pieces. 
But if the lastz run correctly finishes, it is probably fine. I would look how the chains look like.

**Comment by DiegoSafian** [comment]
I split the genome into 20 pieces. But even then Lastz run never stops while producing an output. Could you please check an sample of the axt file (attached in .txt) to check if you see something wrong?
[test.txt](https://github.com/hillerlab/TOGA/files/11068979/test.txt)

**Comment by MichaelHiller** [comment]
Looks OK to me. Not clear what the problem is and why lastz doesn't stop. Maybe make more chunks or try https://github.com/hillerlab/make_lastz_chains ? 

Also, there is lastz v1.04something now.

**Comment by DiegoSafian** [comment]
Thanks. The problem is solved. I tested with a very small file and it finished in a second. So the non-stop is because lastz is still running. I will split into smaller chuncks. Thanks!

**Comment by DiegoSafian** [comment]
Hi,
Sorry, I keep asking questions, but my loss_summ_data.tsv file contains a gene status (UL) that I could not find the meaning of it in the main page.

**Comment by kirilenkobm** [comment]
Hi, 

UL, or "Uncertain Loss," refers to a situation where there is some evidence suggesting the reading frame is corrupted, preventing TOGA from classifying the gene as Intact. However, the evidence is not strong enough to definitively declare the gene as Lost.
