### ISSUE TITLE
Alignment with lastz, axtChain and chainMergeSort

### ISSUE THREAD

**Issue by DiegoSafian** [hillerlab/TOGA#54]
Hi,

I just wanted to know how you generate the alignment with lastz. I understand that the query genome is divided in many parts, resulting in multiple outputs that you need to merge in a single .chain file. Is it correct to use --format=axt in lastz, convert each output independently in .chain with axtChain, and then merge all chain files in one single .chain file using chainMergeSort? so then you can use RepeatFiller.py and others to improve the chain alignment.

All the best,
Diego

**Comment by MichaelHiller** [comment]
Hi Diego, no, all alignments from one reference chromosome (scaffold) need to be pooled and then feed into axtChain. Otherwise, you may fragment your chains. 

https://github.com/hillerlab/make_lastz_chains handles all that.

**Comment by MichaelHiller** [comment]
Pls do
git clone https://github.com/hillerlab/make_lastz_chains.git

**Comment by DiegoSafian** [comment]
Thanks. I am working on this
