### ISSUE TITLE
Re-organizing TOGA-generated gtfs to a per-gene format (similar to what's in NCBI or Ensembl)

### ISSUE THREAD

**Issue by sz-1002** [hillerlab/TOGA#56]
Hi,

I was wondering if you can advise on the best practices to re-organize TOGA-generated annotations to a per-gene format, something like the gtfs/gffs from NCBI or Ensembl, e.g.

gene1
transcript1
transcript2
gene2
transcript1
transcript2
...

I'm mainly wondering about what to do when there are multiple chainIDs for the same gene. Should the transcripts be summarized under each chainID, and different chainIDs be treated as "different genes"? (I'm assuming different chains have no overlaps in genomic positions?)

Thank you very much for your help!

**Comment by MichaelHiller** [comment]
For the first question, TOGA transcripts are named transcriptID.geneSymbol.chainID. So the gene is encoded in the name. 
Also, https://github.com/hillerlab/TOGA/blob/master/TOGAInput/human_hg38/toga.isoforms.tsv lists the assignment of transcripts to genes (which come from Ensembl / NCBI). 

If there are multiple chainIDs, then you typically have >1 co-orthologous loci in the query (at least that is what TOGA inferred). Here it depends what you want to do. You could select the ortholog that is intact (maybe the other is partially intact or uncertain loss). Or you select the ortholog with the higher orthology probability. But there will be cases where all of this is very similar.

**Comment by sz-1002** [comment]
@MichaelHiller 
Thank you!
