### ISSUE TITLE
Any documentation available?

### ISSUE THREAD

**Issue by francicco** [hillerlab/TOGA#62]
Hi,

I'm running consistently TOGA on a 63way genome alignment of butterflies. At the moment is working, and I have no issues.
But because the output is quite extensive I was wondering if there is any documentation available. For example, I was wondering where can I find joining split genes.

Thanks a lot
Francesco

**Comment by MichaelHiller** [comment]
Hi Francesco, 

we have a pretty detailed description of the useful output files here: 
https://genome.senckenberg.de/download/TOGA/README.txt

Pls have a look. Of course, there could be details not documented there. 
Pls point them out and we will add them to the documentation. 

-----
Genes joined from several fragments are indicated by the chainID -1 in the query_annotation.bed file. E.g. ENST00000381683.EIF3L.-1
If you run TOGA, there is a temp folder where this file contains information which chains corresponded to gene fragments: 
g ENST00000381683 temp/gene_fragments.txt
ENST00000381683.EIF3L	72953,287881,53756,33774

The features of each chain are in temp/chain_results_df.tsv 

Best
Michael

**Comment by francicco** [comment]
Hi Michael,

Yes, I saw the readme, I meant something more in depth about the output. In my folder the `gene_framents.txt` doesn't exists, nor any `q_transcript` that ends with `.-1`.  They all have a number `<RefID>.x`, and that `x` correspond to column 3 in `chain_results_df.tsv`. So, I don't quite understand.

- Another thing I don't quite get is the content of `paralogs.txt`. The ids in it do not appear in `orthology_classification.tsv`. Why?
- From the `one2many` or `many2one` is it possible to distinguish and exclude paralogs, ora all of them are equally orthologs?

I have a lot of questions... sorry
cheers
F

**Comment by MichaelHiller** [comment]
Well if you don't have annotations ending with -1 and if there is no gene_fragment.txt, then no gene fragment joining happened. If the genes are rather short (genomic length, including introns) and/or your butterfly assemblies are good, then this is expected. 

paralogs.txt is listing the transcript.gene.chainID for which the chain was classified as a paralog. 

Wrt one2many etc: TOGA's classifier predicts that ALL the 'manys' are co-orthologs. Paralogs are not included in the orthology type.

**Comment by francicco** [comment]
Thanks a lot Michael!

- So, in case i'd want to check for gene expansions, how would I include the paralogs (in- and out- paralogs) in the count?
- How do I check for gene loss? Is it in `loss_summ_data.tsv` and what's the meaning of the 3rd column?

At some point I'll stop asking questions I promise!
: )
F

**Comment by MichaelHiller** [comment]
For gene expansions, you could take a gene family assignment for the reference species, then get all (co-)orthologs for a query species. They would form the family in the query species. I would probably filter for intact, partially intact and uncertain loss status. 

loss_summ lists the classification of the projection (one transcript to one orthologous query locus), per transcript (considering all orthologous loci) and gene (all loci + all transcripts). The status is I=Intact, PI=Partially Intact, UL=Uncertain loss, M=Missing, L=Lost. These are explained in the methods section of the paper https://www.science.org/stoken/author-tokens/ST-1161/full

**Comment by francicco** [comment]
What do you mean by that?
> you could take a gene family assignment for the reference species

You mean column 1 in `orthology_classification.tsv`? Because If I pick `many2one` in `orthology_classification.tsv` I only find one gene id, I'd expect to find also the other reference id that belong to the OG. Right? maybe the other co-orthologs are listed in another table?

Cheers
F

P.S. I was developing a similar tool using CAT, your tool is a lot better! :D

**Comment by francicco** [comment]
Also, I have a quite fragmented genome, but still, TOGA didn't produce any `gene_fragment.txt` output.
F

**Comment by MichaelHiller** [comment]
What I mean is something like this: Say Hoxa genes are a pre-defined gene family. For Each Hoxa1, Hoxa2 etc TOGA infers orthologs. You could then pool the predicted orthologs for Hoxa1, Hoxa2 etc and you have the size of the Hoxa gene family in the query. 
Hope that makes sense. 

All (co)orthologs are listed in the orthology_classification.tsv.

**Comment by MichaelHiller** [comment]
@kirilenkobm
Is there a flag that needs to be set to turn on the gene fragment joining?

**Comment by kirilenkobm** [comment]
@MichaelHiller @francicco 

Yes, pls add the `-f` argument to the TOGA call to activate the fragment joining feature (maybe we should make it default).

- Bogdan

**Comment by MichaelHiller** [comment]
Yes, lets make that default pls. That explains why fragment joining did not happen.

**Comment by francicco** [comment]
Ooh, I see, thanks a lot. Is it possible to resume a previous run with the flag on?

**Comment by francicco** [comment]
@MichaelHiller 

> For Each Hoxa1, Hoxa2 etc TOGA infers orthologs. You could then pool the predicted orthologs for Hoxa1, Hoxa2 etc and you have the size of the Hoxa gene family in the query.

Ok, I see your point, you're actually talking about Gene Family at a broader scale. I was thinking more in an orthologous group, groups within Gene Family. Also, for `many2many` and `many2one`, where can I find the many of the reference species, in other words, all the other paralogs?

Thanks a lot, and gain, very sorry for these many questions.
Cheers
F

**Comment by MichaelHiller** [comment]
OK, I understand. 

Again orthology_classification.tsv only lists orthologs as 
t_gene	t_transcript	q_gene	q_transcript	orthology_class

Here is a many2many case: 
```
grep ZKSCAN3 orthology_classification.tsv 
ENSG00000189298	ENST00000252211.ZKSCAN3	reg_16558	ENST00000252211.ZKSCAN3.213733	many2many
ENSG00000189298	ENST00000252211.ZKSCAN3	reg_10332	ENST00000252211.ZKSCAN3.1599	many2many
ENSG00000189298	ENST00000252211.ZKSCAN3	reg_14134	ENST00000252211.ZKSCAN3.156	many2many
```
TOGA infers 3 co-orthologous gene loci in the query (called reg_num;  we will improve naming in the future).
If you now grep for the 3 reg_num genes, you see which reference genes project to these loci. 
```
grep reg_16558 orthology_classification.tsv 
ENSG00000189298	ENST00000252211.ZKSCAN3	reg_16558	ENST00000252211.ZKSCAN3.213733	many2many
ENSG00000197062	ENST00000623276.ZSCAN26	reg_16558	ENST00000623276.ZSCAN26.41133	many2many
ENSG00000197062	ENST00000421553.ZSCAN26	reg_16558	ENST00000421553.ZSCAN26.41133	many2many
grep reg_10332 orthology_classification.tsv 
ENSG00000189298	ENST00000252211.ZKSCAN3	reg_10332	ENST00000252211.ZKSCAN3.1599	many2many
ENSG00000187626	ENST00000377294.ZKSCAN4	reg_10332	ENST00000377294.ZKSCAN4.156	many2many
grep reg_14134 orthology_classification.tsv 
ENSG00000189298	ENST00000252211.ZKSCAN3	reg_14134	ENST00000252211.ZKSCAN3.156	many2many
ENSG00000187626	ENST00000377294.ZKSCAN4	reg_14134	ENST00000377294.ZKSCAN4.1599	many2many
```
Here ZKSCAN3, 4, 26 form a many2many group with 3 inferred orthologs in the query. 
To systematically extract them, one probably has to write a small script that first reads everything in a hash.


Chains classified as paralogous are listed in temp/paralogs.txt. However, TOGA does not annotate the paralogs (with one exception when the paralogous-classified locus does not get an orthologous projection). In other words, the paralogs are annotated based on their respective ortholog. 
To form paralog groups, I think Blast-clustering the annotated proteins is probably the best. 

@kirilenkobm  Any other ideas here?

**Comment by francicco** [comment]
Great! Thank you @MichaelHiller,

I have a more complete picture. I'm guessing there's no way of resuming the previous run to get the fragmented genes.

Cheers
F

**Comment by MichaelHiller** [comment]
I would suggest to re-run with the -f flag. Sorry

**Comment by kirilenkobm** [comment]
@francicco 

Thank you for your questions. I am planning to write comprehensive TOGA documentation, and your inquiries have helped clarify areas that might be unclear regarding TOGA output.

As for rerunning TOGA with the -f flag: indeed, it was only after reviewing the issues that I realized a feature like "avoid rerunning completed CESAR jobs" is necessary (something like checkpoints).

**Comment by francicco** [comment]
Hi @kirilenkobm,

Yes, I think checkpoints would be a smart thing to implement, it makes exploring possibilities more manageable.
It is really a great tool.

If you want my unrequested feedback, is that a piece of code that puts together the results for different pairwise analyses (e.g.: an orthology table) would be really useful for the user. Something that I'm planning to do myself for my runs, maybe integrating two sets of pairwise runs from different references.

Thanks again!
F

**Comment by kirilenkobm** [comment]
@francicco 

thank you for the valuable feedback. I included respective tasks to my TODO list
We started aggregating documentation here: https://github.com/hillerlab/TOGA/wiki

And I'd prefer to close this issue
