### ISSUE TITLE
Identification of gene vs transcripts losses

### ISSUE THREAD

**Issue by DiegoSafian** [hillerlab/TOGA#64]
Hi,
I have been using toga for some species and I am particularly interested in gene loss. When I check the loss_summ_data.tsv and orthology_classification.tsv I noticed that toga is analyzing the transcript losses rather than genes. I am wondering if it is possible to instruct toga to report genes instead of transcripts so that I do not need to track all transcripts from a gene to summarize the total gene loss.
Example. Toga reports the loss of all these transcripts: 
rna-XM_047385747.1
rna-XM_047385749.1
rna-XM_047385750.1
na-XM_047385751.1 
rna-XM_047385753.1
rna-XM_047385754.1 
rna-XM_047385755.1
 rna-XM_047385756.1
 rna-XM_047385757.1
 rna-XM_047385758.1
 rna-XM_047385759.1
 rna-XM_047385760.1
But all transcripts belong to the same gene X. I would like to have a more summarized result, initially indicating that gene X was lost. Is it possible?

**Comment by MichaelHiller** [comment]
The loss_summ_data.tsv file has 3 types of output
PROJECTION (1 transcript to 1 orthologous query locus)
TRANSCRIPT (1 transcript, taking all (co)orthologous loci into account)
GENE (taking all transcripts into account). 

So you could grep for GENE in this file. 

Of course, you need to tell the TOGA input with the toga.isoforms.tsv file which transcript belongs to which gene.

**Comment by DiegoSafian** [comment]
I have tried several species as references (therefore, several annotation files) and I never get the gene column. I only obtain the projection and transcript in the same column. Should I find the gene at the end of the first column. If I do not find GENE, there no gene was lost?

**Comment by MichaelHiller** [comment]
Has nothing to do with several references. 
How does your  toga.isoforms.tsv look like? I assume this is empty (?)
You need to tell TOGA which transcripts belong to which gene.

**Comment by kirilenkobm** [comment]
Hi @DiegoSafian,

Did you specify reference isoforms using the -i/--isoforms argument?
TOGA recognizes that a reference gene may be represented by multiple isoforms.
Therefore, this file is necessary to match each gene with its respective isoforms.

However, if the isoforms file is not provided, TOGA treats each reference transcript as a separate gene.

**Comment by DiegoSafian** [comment]
Thanks for the info. I did not include the -i. I will work on that now.. Thanks!

**Comment by lhauff** [comment]
Hello,

Is there a recommended way to generate the isoform.tsv file if there is not an Ensembl dataset available for the species of interest?

Best,
Lindsey

**Comment by MichaelHiller** [comment]
Hi Lindsey, 

good question. 
If you have no assignment of transcripts to genes (or gene names), I would suggest 'same strand, exon overlap' to find transcripts that belong to the same gene. 
UCSC's overlapSelect -strand can do that and handles bed12 (meaning exon overlap). Likely bedtools can do that too. 

I think this will work well for almost all genes. The exception are a few genes that overlap on the same strand, but are different genes. E.g. some exons or exon parts have dual coding capacity.

Michael
