### ISSUE TITLE
Nextflow DSL1 is no longer supported

### ISSUE THREAD

**Issue by Threeman8** [hillerlab/TOGA#65]
hi,
I download nextflow by 
`mamba create -n toga -c bioconda nextflow java-jdk -y`

when installing, I put this command:
`(toga) [heweijun@login2 TOGA]$ ./run_test.sh micro`
and appears 
`N E X T F L O W  ~  version 23.04.1
Nextflow DSL1 is no longer supported — Update your script to DSL2, or use Nextflow 22.10.x or earlier
Error! Process nextflow /public/home/heweijun/biosofts/TOGA/execute_joblist.nf --joblist /public/home/heweijun/biosofts/TOGA/micro_test_out/temp/chain_class_jobs_combined died
Program finished with exit code 1`

Could you help me solve this problem?

Thank you~
Best

**Comment by kirilenkobm** [comment]
Hi!

I would suggest downgrading nextflow to 22.10.x (for example, 22.10.4) so that DSL1 is again supported.

Duplicate https://github.com/hillerlab/TOGA/issues/59

**Comment by Threeman8** [comment]
Hi, kirilenkobm
Thanks. You are very helpful.
I don't know how to install 22.10.x from conda, but conda do has a 18.10.1.
So I try
`mamba install -c dfornika nextflow -y`
and it works.

Thanks again
