### ISSUE TITLE
How to get U12 files of other species' genomes

### ISSUE THREAD

**Issue by mengting-Ding** [hillerlab/TOGA#68]
Hi,
Thanks for sharing the tool!
I want to run TOGA with another specie's genome except human, chicken and mouse, such as genome of Neogale vison. Could you please share the method that how to get the U12 file?
Thanks!

**Comment by MichaelHiller** [comment]
We took the U12 intron information from U12DB, but this is a rather old and not regularly updated database. 

There are methods like intronIC (https://academic.oup.com/nar/article/48/13/7066/5850313) to classify introns as U2 (major) and U12 (minor spliceosome) in a gene annotation, which I assume will also work well for mammals in general. 
I don't know which method is the best, but this publication is from 2020.

**Comment by kirilenkobm** [comment]
@mengting-Ding 

pls also note how the U12 file is formatted. It is a tab-separated file with 3 columns.
Column 1 - transcript ID
column 2 - exon number (starting with 1)
Column 3 - D or A character
where D - donor, A - acceptor

Which marks what splice site of this exon is U12.

To be added to documentation.
