### ISSUE TITLE
Too many (108266) CESAR jobs died (v1.1)

### ISSUE THREAD

**Issue by mengting-Ding** [hillerlab/TOGA#72]
Hi, @MichaelHiller,
I had ran TOGA (version 1.0), and it can work well. While using the same input files with the same arguments, I updated the software version to version 1.1, I get the error: "Too many (108266) CESAR jobs died, please check your input data and re-run TOGA. Program finished with exit code 1".
By the way, I noticed the warning: "/opt/service/miniconda3/envs/toga_env/lib/python3.6/site-packages/joblib/_multiprocessing_helpers.py:45: UserWarning: [Errno 28] No space left on device.  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))"
Could you please give me some advice to solve the problems?
Thank you for your help with this!

**Comment by MichaelHiller** [comment]
Likely @kirilenkobm needs to have a look here, 
but pls check if you disk has enough space. The "no space left on device" indicates that you ran out of space ?

**Comment by mengting-Ding** [comment]
Hi, @MichaelHiller 
Thanks for your quick reply and advice! The disk still has enough space. And even when I tried to analyze only one chromosome, I ran into the same problems.

**Comment by MichaelHiller** [comment]
OK. 
This error only occurs with TOGA 1.1 and not with 1.0? 
I'll ask @kirilenkobm  to have a look

**Comment by kirilenkobm** [comment]
Hi @mengting-Ding 

I'm here to help, but I could use a bit more information:

What type of environment are you using to run TOGA? Is it a slurm-operated cluster, a standalone machine with multiple CPU cores, or something else entirely?
Were the results from TOGA 1.0 reasonable? How many lines are in the query_annotation.bed file?
I noticed you're running Python 3.6. Have you considered updating to a more recent version?
Just so you know, joblib is necessary for loading ML models. If you've made it to the CESAR step, it shouldn't have caused any issues.
Could you do me a favor and locate the nextflow logs? You can do this by running TOGA with the --do_not_del_nf_logs flag. Afterwards, look for a directory named "nextflow_logs" in the same directory from which you ran TOGA. Inside, you should find a few directories labeled "cesar_joblist_queue_*". This is where the nextflow logs containing the errors will be. Could you please send them to me so I can figure out what exactly went wrong?

**Comment by mengting-Ding** [comment]
Since disk memory is sufficient, does " No space left on device" mean running out of memory?
I try to expand memory in nextflow_config_files, but this has no effect. Do I need to continue expanding memory settings in nextflow_config_files?
I'm sorry I have so many questions.

**Comment by kirilenkobm** [comment]
@mengting-Ding 
unfortunately, `OSError: [Errno 28] No space left on device` means that it tried to write something into a file and there was insufficient disk space on the device.
The CESAR_wrapper.py crashes when tries to create a temporary "input file" for CESAR2.0.

by default, on UNIX systems, it writes such files into "/dev/shm/{whoami}", and into "/tmp/{whoami}" if the "/dev/shm/" does not exist. Now I understand that it could be not the best solution.
I guess, on some systems that simply would not work.
I will fix this issue today - these temp files will be saved to a directory provided by user (I will add some parameter to toga.py, like `--temp_dir_for_cesar_in`)

Thx for your patience

**Comment by kirilenkobm** [comment]
Btw, I guess the input file is not strictly needed here, I can pass the input directly into CESAR's stdin. 
I will keep you updated.

**Comment by kirilenkobm** [comment]
@mengting-Ding 

pls try the most recent TOGA version.
It does not create temporary input files for CESAR and redirects the input data directly into CESAR's stdin.

**Comment by mengting-Ding** [comment]
@kirilenkobm  thanks a lot!

**Comment by kirilenkobm** [comment]
@mengting-Ding did it work? =)

**Comment by mengting-Ding** [comment]
Hi @kirilenkobm,
TOGA1.1.4 is running, and it needs some time. I will tell you the result whether it is successful or not.
Your help has been very helpful to me. Thank you again.

**Comment by mengting-Ding** [comment]
Hi @kirilenkobm  and @MichaelHiller ,
I installed the latest version of the TOGA and it works fine!
Thanks for your patient help!
