### ISSUE TITLE
TOGA crashes during micro test at STEP 2, which uses nextflow 

### ISSUE THREAD

**Issue by smorzechowski** [hillerlab/TOGA#75]
Dear TOGA Developers, I am extremely excited to use your tool on my new genomes! I have encountered an error when running ./run_test.sh micro after installing everything as recommended. The following error continues to appear and I cannot figure out why --

```
#### STEP 2: Extract chain features: parallel step

Extract chain features, project name: micro_test_out_chain_feats_at_1687524890
Project path: /n/home09/smorzechowski/bin/TOGA/./nextflow_logs/micro_test_out_chain_feats_at_1687524890
Calling nextflow /n/home09/smorzechowski/bin/TOGA/execute_joblist.nf --joblist /n/home09/smorzechowski/bin/TOGA/micro_test_out/temp/chain_class_jobs_combined
N E X T F L O W  ~  version 23.04.2
Error! Process nextflow /n/home09/smorzechowski/bin/TOGA/execute_joblist.nf --joblist /n/home09/smorzechowski/bin/TOGA/micro_test_out/temp/chain_class_jobs_combined died
Program finished with exit code 1
```
The log files just say that TOGA crashed, and don't give me much indication as to why.

```
[smorzechowski@holylogin04 micro_test_out]$ ls
CRASHED  project_args.json  q2bit.link  t2bit.link  temp  version.txt
[smorzechowski@holylogin04 micro_test_out]$ cat CRASHED
TOGA CRASHED AT 2023-06-23 08:54:59.658958
[smorzechowski@holylogin04 micro_test_out]$
```

I am running TOGA and nextflow on a computing cluster that uses slurm. Thus, the configuration files in the `nextflow_config_files` directory should be working just fine, as you indicated in the installation instructions. I assume something is not quite right with my nextflow configuration, but never having used it before, I am not sure what the issue might be. 

Here are the config settings I am using for `extract_chain_features_config.nf`
```
// SLURM config for chain features extraction jobs
// relatively lightweighted jobs
process.executor = 'slurm'
process.queue = 'batch'
process.memory = '10G'
process.time = '1h'
process.cpus = 1
```
And here is head of the modified sbatch script I am using to run the micro test:
```
#!/usr/bin/env bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p test
#SBATCH -e toga%A.err
#SBATCH -o toga%A.out
#SBATCH -J toga
#SBATCH --mem=10G
#SBATCH --time=01:00:00
#SBATCH --account=oeb275r

module load python
module load jdk/20.0.1-fasrc01

export PATH=/n/home09/smorzechowski/bin:$PATH
```

Let me know if you have any insights on what might be going wrong!

**Comment by MichaelHiller** [comment]
@kirilenkobm (Bogdan) mentioned that TOGA right now does not work with NextFlow 2.0. 
He is working on a fix. 
If you can, pls try to install NextFlow 1 instead of 2.

**Comment by smorzechowski** [comment]
That's excellent to know, many thanks for the extremely prompt reply! I will give that a go for now.

**Comment by smorzechowski** [comment]
Thanks, again, I had success running version 19.12.0-edge of Nextflow. TOGA completed the micro test successfully!
