### ISSUE TITLE
TOGA installation - ./run_test.sh micro fail

### ISSUE THREAD

**Issue by aravindpad** [hillerlab/TOGA#79]
Hi,
I'm configuring TOGA on an HPC cluster running SLURM.
When I run the test it fails with the following message.

N E X T F L O W  ~  version 23.04.1
Nextflow DSL1 is no longer supported — Update your script to DSL2, or use Nextflow 22.10.x or earlier
Error! Process nextflow /xxxxxxxxxx/toga/TOGA/execute_joblist.nf --joblist /xxxxx/toga/TOGA/micro_test_out/temp/chain_class_jobs_combined died
Program finished with exit code 1

I'm an admin but not familiar with the tools, Any help is greatly appreciated.

**Comment by kirilenkobm** [comment]
Hi @aravindpad 

Please try the updated TOGA version 1.1.3. The issue with Nextflow DSL2 should now be resolved.
