### ISSUE TITLE
Hi @aravindpad

### ISSUE THREAD

**Issue by aravindpad** [hillerlab/TOGA#83]
Hi @aravindpad 

Please try the updated TOGA version 1.1.3. The issue with Nextflow DSL2 should now be resolved.

_Originally posted by @kirilenkobm in https://github.com/hillerlab/TOGA/issues/79#issuecomment-1615836517_
     

HI,
Thank you for your comment.
I did the 1.13. But running into new issue now.
While doing the pip3 install I'm specifying a custom directory as  I want the packages to go to the module space and not the user /.local.
python3 -m pip install -r requirements.txt --target /xxxxx/centos7/toga/1.13/

Error:
Traceback (most recent call last):
  File "/xxxx/centos7/toga/1.13/TOGA/train_model.py", line 5, in <module>
    import xgboost as xgb
  File "/home/xxxx/.local/lib/python3.9/site-packages/xgboost/__init__.py", line 7, in <module>
    from . import collective, dask, rabit
  File "/home/xxx/.local/lib/python3.9/site-packages/xgboost/collective.py", line 9, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Model created
CESAR installation found
Configure successful!
Running test in the micro mode
Calling ./toga.py test_input/align_micro_sample.chain test_input/annot_micro_sample.bed          test_input/hg38.micro_sample.2bit test_input/q2bit_micro_sample.2bit          --pn micro_test_out  --kt          --cjn 1 --chn 1 --ms
Traceback (most recent call last):
  File "/xxxxx/centos7/toga/1.13/TOGA/./toga.py", line 19, in <module>
    from modules.common import parts
  File "/xxxxx/centos7/toga/1.13/TOGA/modules/common.py", line 6, in <module>
    import h5py
ModuleNotFoundError: No module named 'h5py'
(/xxxxx/centos7/toga/1.13) [xxx@hxxxxx TOGA]$ which python
/xxx/centos7/toga/1.13/bin/python

Can you help
Thanks

**Comment by kirilenkobm** [comment]
Hi @aravindpad 

I believe a virtual environment fits better in your case, pls give it a try

**Comment by kirilenkobm** [comment]
@aravindpad 

I had a closer look at the logs.
1. The xgboost library is trying to import numpy from a different location (the user's local directory), rather than the custom location where it was installed.
2. The script can't find the h5py library.
Both issues are likely due to the PYTHONPATH not being set correctly to include the target directory where the packages were installed. 

You can add the target directory to the PYTHONPATH by:
```
export PYTHONPATH=/xxxxx/centos7/toga/1.13:$PYTHONPATH
```

Please let me know whether it works.

**Comment by aravindpad** [comment]
> @aravindpad
> 
> I had a closer look at the logs.
> 
>     1. The xgboost library is trying to import numpy from a different location (the user's local directory), rather than the custom location where it was installed.
> 
>     2. The script can't find the h5py library.
>        Both issues are likely due to the PYTHONPATH not being set correctly to include the target directory where the packages were installed.
> 
> 
> You can add the target directory to the PYTHONPATH by:
> 
> ```
> export PYTHONPATH=/xxxxx/centos7/toga/1.13:$PYTHONPATH
> ```
> 
> Please let me know whether it works.

HI,
Thank you so much.
That worked.
Much appreciated.
