### ISSUE TITLE
Issue with TOGA (too many CESAR jobs died)

### ISSUE THREAD

**Issue by Alchimic007** [hillerlab/TOGA#84]
Hello Bogdan,
Sorrty to bother you, but I have an issue with TOGA, in particular with last test. You see, when I run the code from main node terminal trough command line TOGA runs smoothly and no errors observed. But when I try to run TOGA from bash script it runs with an error "Too many (3546) CESAR jobs died, please check your input data and re-run TOGA
Program finished with exit code 1" on step 7. 
**### Here is my configuration:**
server: slurm
run on the virtual anaconda environment

script:  !/bin/bash

#SBATCH --job-name=TOGA_TEST
#SBATCH --output=/storage/users/mprylutskyi/TOGA/log/T%A_%a.log
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=100GB

$ conda init bash

conda config --set auto_activate_base True

source ~/.bashrc

conda activate condaenv
 
 ./toga.py test_input/hg38.mm10.chr11.chain test_input/hg38.genCode27.chr11.bed /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --kt --pn Max -i supply/hg38.wgEncodeGencodeCompV34.isoforms.txt --nc ./nextflow_config_files --nd ./nextflow_logs --cb 3,5 --cjn 500 --u12 supply/hg38.U12sites.tsv --ms

### Nextflow configuration

**cesar_config_template** 
SLURM config file for CESAR jobs (not bigmem)
// since CESAR have various memory requirements, this
// is just a template, TOGA will fill this itself
// depending on the CESAR job bucket
process.executor = 'local'
process.queue = 'long-24core'
process.time = '24h'  // mostly 8h is enough, just for robustness
process.memory = "${_MEMORY_}G"  // to be replaced
process.cpus = 1  // CESAR utilizes a single core only
executor.queueSize = 1000  // nextflow default is 100 - too few

**cesar_bigmem_config**

// SLURM config for bigmem CESAR jobs
// these jobs require huge amounts of memory and
// take too long
process.executor = 'local'
process.queue = 'long-24core'
process.memory = '500G'
process.time = '24h'
process.cpus = 1

**extract_chain_features_config**

// SLURM config for chain features extraction jobs
// relatively lightweighted jobs
process.executor = 'local'
process.queue = 'long-24-core'
process.memory = '10G'
process.time = '1h'
process.cpus = 1

I would be very grateful for any help.
Kind regards,
Max

**Comment by Alchimic007** [comment]
Thanks for answering that fast. About the first, when I left "batch", or "sbatch" in process.queue line in all config files it ended with an error "sbatch is not a partition command" or something like that. If it is not right then how should I change it? About the cesar log, I have it. Should I send it to you somehow or copy one of "rejected" cesar log files like text?

**Comment by Alchimic007** [comment]
Here is one of CESAR job log file: 

/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000524803 101 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3
/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000228136 49 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3
/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000393282 39 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3
/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000639386 27 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3
/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000542531 39 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3
/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000319856 27 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3
/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000309295 73 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3

**Comment by Alchimic007** [comment]
here is one from rejected log files
/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000524803 101 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3	CESAR JOB FAILURE	whoami: cannot find name for user ID 1578673858 Traceback (most recent call last):   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2979, in <module>     realign_exons(cmd_args)   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2848, in realign_exons     cesar_in_data, cesar_in_filename, is_temp = make_cesar_in(prepared_exons, query_sequences, ref_ss_data, args["cesar_input_save_to"])                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1360, in make_cesar_in     cesar_in_filename, is_temp = make_in_filename(cesar_in_filename)                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1303, in make_in_filename     whoami = subprocess.check_output("whoami", shell=True).decode("utf-8")[:-1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 466, in check_output     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 571, in run     raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command 'whoami' returned non-zero exit status 1. 
/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000228136 49 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3	CESAR JOB FAILURE	whoami: cannot find name for user ID 1578673858 Traceback (most recent call last):   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2979, in <module>     realign_exons(cmd_args)   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2848, in realign_exons     cesar_in_data, cesar_in_filename, is_temp = make_cesar_in(prepared_exons, query_sequences, ref_ss_data, args["cesar_input_save_to"])                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1360, in make_cesar_in     cesar_in_filename, is_temp = make_in_filename(cesar_in_filename)                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1303, in make_in_filename     whoami = subprocess.check_output("whoami", shell=True).decode("utf-8")[:-1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 466, in check_output     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 571, in run     raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command 'whoami' returned non-zero exit status 1. 
/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000393282 39 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3	CESAR JOB FAILURE	whoami: cannot find name for user ID 1578673858 Traceback (most recent call last):   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2979, in <module>     realign_exons(cmd_args)   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2848, in realign_exons     cesar_in_data, cesar_in_filename, is_temp = make_cesar_in(prepared_exons, query_sequences, ref_ss_data, args["cesar_input_save_to"])                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1360, in make_cesar_in     cesar_in_filename, is_temp = make_in_filename(cesar_in_filename)                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1303, in make_in_filename     whoami = subprocess.check_output("whoami", shell=True).decode("utf-8")[:-1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 466, in check_output     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 571, in run     raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command 'whoami' returned non-zero exit status 1. 
/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000639386 27 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3	CESAR JOB FAILURE	whoami: cannot find name for user ID 1578673858 Traceback (most recent call last):   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2979, in <module>     realign_exons(cmd_args)   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2848, in realign_exons     cesar_in_data, cesar_in_filename, is_temp = make_cesar_in(prepared_exons, query_sequences, ref_ss_data, args["cesar_input_save_to"])                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1360, in make_cesar_in     cesar_in_filename, is_temp = make_in_filename(cesar_in_filename)                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1303, in make_in_filename     whoami = subprocess.check_output("whoami", shell=True).decode("utf-8")[:-1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 466, in check_output     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 571, in run     raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command 'whoami' returned non-zero exit status 1. 
/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000542531 39 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3	CESAR JOB FAILURE	whoami: cannot find name for user ID 1578673858 Traceback (most recent call last):   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2979, in <module>     realign_exons(cmd_args)   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2848, in realign_exons     cesar_in_data, cesar_in_filename, is_temp = make_cesar_in(prepared_exons, query_sequences, ref_ss_data, args["cesar_input_save_to"])                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1360, in make_cesar_in     cesar_in_filename, is_temp = make_in_filename(cesar_in_filename)                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1303, in make_in_filename     whoami = subprocess.check_output("whoami", shell=True).decode("utf-8")[:-1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 466, in check_output     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 571, in run     raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command 'whoami' returned non-zero exit status 1. 
/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000319856 27 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3	CESAR JOB FAILURE	whoami: cannot find name for user ID 1578673858 Traceback (most recent call last):   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2979, in <module>     realign_exons(cmd_args)   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2848, in realign_exons     cesar_in_data, cesar_in_filename, is_temp = make_cesar_in(prepared_exons, query_sequences, ref_ss_data, args["cesar_input_save_to"])                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1360, in make_cesar_in     cesar_in_filename, is_temp = make_in_filename(cesar_in_filename)                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1303, in make_in_filename     whoami = subprocess.check_output("whoami", shell=True).decode("utf-8")[:-1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 466, in check_output     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 571, in run     raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command 'whoami' returned non-zero exit status 1. 
/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py ENST00000309295 73 /storage/users/mprylutskyi/TOGA/Max/temp/toga_filt_ref_annot.hdf5 /storage/users/mprylutskyi/TOGA/Max/temp/genome_alignment.bst /storage/users/mprylutskyi/TOGA/hg38.2bit /storage/users/mprylutskyi/TOGA/mm10.2bit --cesar_binary /storage/users/mprylutskyi/TOGA/CESAR2.0/cesar --uhq_flank 50 --mask_stops --check_loss --alt_frame_del --memlim 3	CESAR JOB FAILURE	whoami: cannot find name for user ID 1578673858 Traceback (most recent call last):   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2979, in <module>     realign_exons(cmd_args)   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2848, in realign_exons     cesar_in_data, cesar_in_filename, is_temp = make_cesar_in(prepared_exons, query_sequences, ref_ss_data, args["cesar_input_save_to"])                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1360, in make_cesar_in     cesar_in_filename, is_temp = make_in_filename(cesar_in_filename)                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 1303, in make_in_filename     whoami = subprocess.check_output("whoami", shell=True).decode("utf-8")[:-1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 466, in check_output     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/storage/users/mprylutskyi/.conda/envs/condaenv/lib/python3.11/subprocess.py", line 571, in run     raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command 'whoami' returned non-zero exit status 1.

**Comment by Alchimic007** [comment]
As for the nextflow log I only have an old one made today but it's old with this error:
 error [nextflow.exception.ProcessFailedException]: Error submitting process 'execute_jobs (21)' for execution
Jul-10 11:13:19.147 [Task submitter] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: /storage/users/mprylutskyi/TOGA/nextflow_logs/test_chain_feats_at_1688987589/work/96/e9d6e894f127c0f301673a569799fe/.command.log
Jul-10 11:13:19.148 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'execute_jobs (21)'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  sbatch: error: invalid partition specified: batch
  sbatch: error: Batch job submission failed: Invalid partition name specified

Work dir:
  /storage/users/mprylutskyi/TOGA/nextflow_logs/test_chain_feats_at_1688987589/work/96/e9d6e894f127c0f301673a569799fe

**Comment by Alchimic007** [comment]
New nextflow log files were not created after I changed "batch" to "long-24 core" and "slurm" to "local"

**Comment by kirilenkobm** [comment]
Hi @Alchimic007 

thank you for providing the logs.
Let's break the issues down.

```
whoami: cannot find name for user ID 1578673858 Traceback (most recent call last): File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2979, in realign_exons(cmd_args) File "/storage/users/mprylutskyi/TOGA/CESAR_wrapper.py", line 2848, in realign_exons cesar_in_data, cesar_in_filename, is_temp = make_cesar_in(prepared_exons, query_sequences, ref_ss_data, args["cesar_input_save_to"])
```

the function `get_temp_dir` in the `extract_codon_alignment.py` crashes because the command `whoami` does not work correctly on your system in the given environment. It has never been an issue, but it would be easy to fix.
I will add the fix to the next commit.

Regarding partitions: it depends on your individual cluster configuration.
I just pointed out that you provided different queues for cesar and chain processes: one has additional dash, another is not, I suspect there is a typo.

To get a list of partitions available on your slurm cluster just call `sinfo` on the master node.

**Comment by kirilenkobm** [comment]
JFYI - in the latest TOGA version, the /dev/shm and /tmp partitions are no longer used, and the whoami command too

**Comment by Alchimic007** [comment]
Hello again, thank you for help. Could you explain, if it means that I can reinstall TOGA and try again? I'm very appreciated for your help.
Kind regards,
Max
