### ISSUE TITLE
output fasta for proteomics?

### ISSUE THREAD

**Issue by neely** [hillerlab/TOGA#85]
General question:
Not to be dense, but I am not sure which files might be usable for searching mass spec data. The prot.fasta has both query and reference sequences, and has gaps within entries from the alignment. Is there another argument to generate a fasta with predicted coding sequences only of the query genome?

**Comment by MichaelHiller** [comment]
Hi Ben, 

right, prot.fasta contains the alignments between reference and query for ALL projections (one transcript aligned to one orthologous locus). 
That means if a projection is classified as lost, it will still be contained. 
Likewise, if the query locus has large assembly gaps, the resulting query sequence may be just '-'. 

I assume for mass spec, you want high sensitivity, so I would not filter for projections classified as intact, partially intact or uncertain loss (can be done with loss_summ_data.tsv). 

I know this is a hack and we should probably write a little script, but this 
`cat prot.fasta | grep "PROT | QUERY" -w -A 1 | grep "^\-\-$" -v | awk '{if ($1 ~ /^>/) printf $1"\t"; else print $0}' | sed 's/-//g' | awk -F "\t" '{if ($2 != "") print $1"\n"$2}'`
extracts only the query proteins in fasta, removes '-' and all projections that have no seq.

**Comment by neely** [comment]
Thanks! I love a good awk grep sed command, but had to go find my old MBP to run it. B-)

This definitely cleans it up into something that looks like a normal mammalian fasta. I am going to do some basic comparisons of your TOGA runs and some of the RefSeq runs of the same species, both against each other but also in how they identify bottom up tandem mass spectra taken from these species.

HUGE help for real, thank you!

**Comment by kirilenkobm** [comment]
TODO: document use case here (https://github.com/hillerlab/TOGA/wiki/Interpreting-results)
