### ISSUE TITLE
Problems with installation ./run_test.sh micro 

### ISSUE THREAD

**Issue by giovannaVeiga** [hillerlab/TOGA#88]
Hi, 

I am having trouble with TOGA installation when running the ./run_test.sh micro command. It reports the following error message:

Model found
CESAR installation found
Command finished with exit code 0.
Version 1.1.5
Commit: e5d519200be9e392dcd3ec29ddfca2ee18b20a6e
Branch: master

Calling cmd:
/dados/giovanna/softwares/TOGA/./modules/chain_score_filter test_input/align_micro_sample.chain 15000 > /dados/giovanna/softwares/TOGA/micro_test_out/temp/genome_alignment.chain

/bin/sh: /dados/giovanna/softwares/TOGA/./modules/chain_score_filter: No such file or directory
Please check if you use a proper chain file.
Error! Process:
/dados/giovanna/softwares/TOGA/./modules/chain_score_filter test_input/align_micro_sample.chain 15000 > /dados/giovanna/softwares/TOGA/micro_test_out/temp/genome_alignment.chain
died! Abort.
Program finished with exit code 1

Any thoughts on what may be wrong?

Thanks in advance

**Comment by MichaelHiller** [comment]
Looks like an imcomplete installation to me. Maybe TOGA recognized that CESAR is already installed and then skipped over installing modules it needs. 

Can you pls try to wipe CESAR and TOGA and reinstall from scratch? 
Otherwise, we need @kirilenkobm  to have a look. 

Thx

**Comment by kirilenkobm** [comment]
@giovannaVeiga seems like the C code was not compiled, pls try rerunning `./configure.sh` in the TOGA installation directory.

**Comment by giovannaVeiga** [comment]
I run the ./configure.sh inside the TOGA directory and from outside. The first give me the following output:

**Comment by giovannaVeiga** [comment]
Thank you @kirilenkobm. I ran ./configure.sh inside the TOGA directory and got the following message:
Model found
Found CESAR installation

The CESAR2.0 directory is inside the TOGA directory, as well as the executable file. But as soon as I run the ./run_test.sh micro (also in the TOGA directory) the same error message appears. 

I thought maybe the test didn't complete because the server I was using didn't have enough computing power to run the test.

**Comment by giovannaVeiga** [comment]
Hi @MichaelHiller and @kirilenkobm,

Sorry for the late update. Just to let you all know, I got to run TOGA, however, I needed to use a Virtual machine, because the server compiler version I was using was not compatible with the TOGA installing requirements. Anyway, it is working now and I hope to get the results for my data soon!

Thank you again for the help

**Comment by kirilenkobm** [comment]
Hi @giovannaVeiga,

Thank you for the update. That sounds pretty interesting because these build commands don't contain anything special and work on M1 Macs, x86_64 Ubuntu, CentOS, and many others. Just out of curiosity, which gcc compiler is used on your server?

**Comment by giovannaVeiga** [comment]
Hi @kirilenkobm,
The gcc from the server is gcc (GCC) 12.2.0 and the virtual machine is (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0. 
If it helps, when I installed the TOGA on the server, I got error messages like the image below, something that didn't happen in the virtual machine.

![image](https://github.com/hillerlab/TOGA/assets/82518932/813bd896-70f4-452e-8d18-ac5b1c543965)

**Comment by kirilenkobm** [comment]
Thank you for sharing this...  it could happen due to a variety of reasons like a mismatch in GCC versions, OS differences, or even some corrupted state on that specific machine. Maybe, you have another GCC installed on the server (not only 12.2.0). But it definitely lies beyond the scope of the pipeline.
