### ISSUE TITLE
Nextflow issue

### ISSUE THREAD

**Issue by dianamosa** [hillerlab/TOGA#9]
Hello,

I installed TOGA in slurm, the micro test ran without any issues, however I am having issues with the final test.

First, I got the following error during the Extract chain step:

```
Error executing process > 'execute_jobs (64)'
Caused by:
  Failed to submit process to grid scheduler for execution
Command executed:
  sbatch .command.run
Command exit status:
  1
Command output:
  sbatch: error: The 'batch' is not a valid partition. (Available partitions for 'default' account: [gpu-build,nocona,matador,quanah])
  sbatch: error: Batch job submission failed: Unspecified error
```

I edited the config files as follows: process.queue='nocona'. By doing this, the error was fixed, however now I am getting a new error.

```
Error executing process > 'execute_jobs (5)'
Caused by:
  Failed to submit process to grid scheduler for execution
Command executed:
  sbatch .command.run
Command exit status:
  1
Command output:
  sbatch: error: Number of nodes must be specified: [-N, --nodes=<num>]
  sbatch: error: Batch job submission failed: Node count specification invalid
```

I checked on the nextflow documentation and I don't see a process option to assign the number of nodes in the job submission script. 
Have you seen this issue before?

Thank you,

Diana Moreno

**Comment by kirilenkobm** [comment]
Probably is not relevant anymore
