### ISSUE TITLE
Some chromosomes present in the chain/bed file are not found in the Two bit file

### ISSUE THREAD

**Issue by igorpop0v** [hillerlab/TOGA#94]
Dear TOGA Developers,

Thank you very much for your innovative software for gene annotation.

I am working on gene annotation of a newly assembled genome (~1400 scaffolds) and trying to annotate it using TOGA with hg38 as a reference/target genome.

After running the following command I am getting the error that some chromosomes present in the chain/bed file are not found in the Two bit file (I guess the reference genome?).

The command: /home/popov/TOGA/toga.py /home/popov/flo_my_gen/run/liftover.chain /home/popov/TOGA/supply/hg38.wgEncodeGencodeCompV34.bed /home/popov/Human_genome_38/GRCh38.primary_assembly.genome_n.2bit /home/popov/flo_my_gen/run/source.2bit --kt --pn TOGA_my_gen --nc /home/popov/TOGA/nextflow_my_configs -i /home/popov/TOGA/supply/hg38.wgEncodeGencodeCompV34.isoforms.txt --cjn 36 --u12 /home/popov/TOGA/supply/hg38.U12sites.tsv --ms

The output: 
#### Initiating TOGA class ####
Version 1.1.5
Commit: 2449d3156413fbad090a8bdf51f03e50ccb9c185
Branch: master

Calling cmd:
/home/popov/TOGA/modules/chain_score_filter /home/popov/flo_my_gen/run/liftover.chain 15000 > /home/popov/TOGA_my_gen/temp/genome_alignment.chain

Command finished with exit code 0.
Writing isoforms data for 36581 transcripts.
Found 194 sequences in /home/popov/Human_genome_38/GRCh38.primary_assembly.genome_n.2bit
Found 194 sequences in /home/popov/Human_genome_38/GRCh38.primary_assembly.genome_n.2bit
Error! 2bit file: /home/popov/Human_genome_38/GRCh38.primary_assembly.genome_n.2bit; chain/bed file: /home/popov/TOGA_my_gen/temp/genome_alignment.chain; Some chromosomes present in the chain/bed file are not found in the Two bit file. First <=100: scaffold_989
scaffold_585
scaffold_18
scaffold_526
scaffold_775
scaffold_855
scaffold_897
scaffold_983
scaffold_1420
scaffold_500
scaffold_1408
scaffold_807
scaffold_205
scaffold_1085
scaffold_433
scaffold_862
scaffold_1232
scaffold_1038
scaffold_985
scaffold_1241
scaffold_864
scaffold_1169
scaffold_141
scaffold_71
scaffold_191
scaffold_1071
scaffold_246
scaffold_1032
scaffold_568
scaffold_1416
scaffold_722
scaffold_524
scaffold_75
scaffold_147
scaffold_57
scaffold_342
scaffold_1206
scaffold_1126
scaffold_747
scaffold_975
scaffold_38
scaffold_168
scaffold_1191
scaffold_306
scaffold_1171
scaffold_310
scaffold_978
scaffold_718
scaffold_293
scaffold_1376
scaffold_1079
scaffold_409
scaffold_393
scaffold_1255
scaffold_1215
scaffold_279
scaffold_202
scaffold_558
scaffold_1229
scaffold_1100
scaffold_689
scaffold_247
scaffold_690
scaffold_1335
scaffold_49
scaffold_830
scaffold_799
scaffold_910
scaffold_384
scaffold_1107
scaffold_1132
scaffold_1199
scaffold_880
scaffold_1419
scaffold_492
scaffold_186
scaffold_860
scaffold_331
scaffold_215
scaffold_153
scaffold_351
scaffold_813
scaffold_811
scaffold_180
scaffold_1270
scaffold_696
scaffold_468
scaffold_370
scaffold_1413
scaffold_746
Program finished with exit code 1

Can you please tell what could be the problem?

As far as I know, there are no scaffolds in the reference hg38, as this genome contains nearly complete chromosome assemblies.
Then why does the command try to find scaffolds in the 2bit file? As I understand, these scaffolds are listed in the chain file, because they were aligned to chromosomes from the reference genome and come from my genome assembly. 
Then why should they be found in the 2bit file of the reference/target genome?

Again, thank you very much for your software. It is really great and novel.

**Comment by MichaelHiller** [comment]
I assume the chains were not made with the same 2bit that you now use for TOGA. 

Pls use the hg38 from https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.2bit 
which does not have "scaffold_*" names, but chr1-chrX,Y (and a bunch of _alt, _fix and _random scaffolds that we ignore). 

Let us know if that is not the problem.

**Comment by igorpop0v** [comment]
Dear @MichaelHiller,

Thank you very much for your kind reply.
The problem was in the chain file.

Initially, it looked like this:

chain 2829 scaffold_402 1599642 + 255863 255893 chr6 170805979 - 56704105 56704135 1997214
30

chain 4618 scaffold_402 1599642 + 288875 288926 chr1 248956422 + 16557768 16557819 145529
51

chain 3202 scaffold_402 1599642 + 345414 345448 chr12 133275309 - 99754583 99754617 793225
34

When I changed the "source" and "target" genomes, the chain file became looking like this:

chain 1388 chr1 248956422 + 10288 10320 scaffold_138 1531771 - 637572 637604 4580
32

chain 1969 chr1 248956422 + 10397 10464 scaffold_1016 29613 + 104 158 960
30	13	0
24

chain 2856 chr1 248956422 + 27275 27305 scaffold_671 28543727 + 16412626 16412656 1254558
30

chain 3075 chr1 248956422 + 43835 43868 scaffold_57 35153020 + 1258022 1258055 922701
33

So users should be careful with generating proper chain files.

Thank you and @kirilenkobm for the software and time in resolving issues.

**Comment by igorpop0v** [comment]
Dear @MichaelHiller,

Thank you very much for your kind reply.
The problem was in the chain file.

Initially, it looked like this:

chain 2829 scaffold_402 1599642 + 255863 255893 chr6 170805979 - 56704105 56704135 1997214
30

chain 4618 scaffold_402 1599642 + 288875 288926 chr1 248956422 + 16557768 16557819 145529
51

chain 3202 scaffold_402 1599642 + 345414 345448 chr12 133275309 - 99754583 99754617 793225
34

When I changed the "source" and "target" genomes, the chain file became looking like this:

chain 1388 chr1 248956422 + 10288 10320 scaffold_138 1531771 - 637572 637604 4580
32

chain 1969 chr1 248956422 + 10397 10464 scaffold_1016 29613 + 104 158 960
30 13 0
24

chain 2856 chr1 248956422 + 27275 27305 scaffold_671 28543727 + 16412626 16412656 1254558
30

chain 3075 chr1 248956422 + 43835 43868 scaffold_57 35153020 + 1258022 1258055 922701
33

So users should be careful with generating proper chain files.

Thank you and @kirilenkobm for the software and time in resolving issues.
