### ISSUE TITLE
Computational requirement to process human genome and one bat genome with Make Lastz Chains and TOGA

### ISSUE THREAD

**Issue by philge** [hillerlab/TOGA#96]
Hi,

Can you please tell me what it would take computationally (capacity and time) to process human genome reference, and one bat genome through the toga process including Make Lastz Chains?

Thanks
Philge

**Comment by kirilenkobm** [comment]
https://github.com/hillerlab/TOGA/wiki/Installation-and-configuration
TODO: finish the respective section
