### ISSUE TITLE
Using multiple references?

### ISSUE THREAD

**Issue by AnnaAMonaco** [hillerlab/TOGA#99]
Hi, thank you for this great tool. 

I had a simple question and I couldn't find if it had been asked before: can we use two references at the same time for orthology query? 

For example: I am trying to improve gene annotations for the domestic pig references susScr11, and I would like to use TOGA to find orthologs both based on mouse because this is my comparison species, but also based on human as this is more closely related to pig. In this case I am more interested in annotating gene names to susScr11 transcripts that still only have an "ENSUSxyz" name. I just wanted to know if there is a way of doing this in one go, or if I have to run TOGA twice (pig vs mouse, pig vs human) and then sort of "intersect" the two new bed files to keep unique information from both comparisons. 

Thanks in advance for any advice :)

Anna

**Comment by MichaelHiller** [comment]
Likely, we won't change TOGA to simulateously run >1 reference (this would need a parallel processing of 2 chain files among many other things). 

But TOGA can be run independently with >1 reference. The resulting query_annotation.bed files can be combined. 
Alternatively, one can extract and combine only the transcripts that are classified as Intact or Partially Intact.

**Comment by kirilenkobm** [comment]
To be explained here: https://github.com/hillerlab/TOGA/wiki/Usage-and-best-practices
